Map<String, String> en() {
  return {
    "contactSaved": "Contact saved successfully",
    "Saved": "Saved",
    "errorLine1": "Something went wrong, please try again later",
    "contactPermissionRequired": "Contact permission is required",
    "noInternetConnection": "Please check your Internet connection",
    "internetSpeed": "Your Internet speed",
    "goodInternetConnection": "You Can Take Internet Calling",
    "badInternetConnection": "You Will Face Internet Call Issues.",
    "timeoutMessage":
        "Something went wrong.\nPlease check you internet connection and please try again.",
    "today": "Today",
    'resignation': 'Resignation',
    'leaveresignation': "Leave / Resignation",
    'noDataToShow': 'No data to show',
    'deleteChat': 'Delete Chat',
    "followers": "Followers",
    'voucherPopUpTitle': 'Choose The Gift Voucher To Send',
    "dasha": "Dasha",
    "version": "Version",
    "somethingWentWrong": "Something went wrong",
    "total": "@count Total",
    'bhavChalitChart': 'Bhav Chalit Chart',
    "noticeBoard": "Notice board",
    "totalAvailability": "Total Availability",
    "last30Days": "Last 30 Days",
    "last30DaysDes":
        "This is your last 30 days availability. Where,'Available' is when you're online and waiting for clients, and 'Busy' is when you're talking to them in chats, calls, or live sessions.",
    "totalAvailabilityDes":
        "This is your current day availability. Where,'Available' is when you're online and waiting for clients, and 'Busy' is when you're talking to them in chats, calls, or live sessions.",
    "noticeBoardDes":
        "Here, you'll find essential information that keeps you connected and informed about what's new and what's next.",
    'cusps': 'Cusps',
    'cusp': 'Cusp',
    "viewAll": "View All",
    "poojaDetails": "Pooja Details",
    'planets': 'Planets',
    'rulingPlanets': 'Ruling Planets',
    'vimshottari': 'Vimshottari',
    "message": "Message",
    "senderCategory": "Sender Category",
    "readMore": "Read more",
    "readLess": "Read less",
    "kp": "KP",
    "reportingQue": "Why are you reporting this",
    "showLess": "Show less",
    "goLive": "Go Live",
    "live": "Live",
    "feedbackValidation": "Please Enter your feedback",
    "congratulations": "Congratulations",
    "tips": "Tips",
    "inMins": "in mins",
    "last30DaysAvailability": "Last 30 Days Availability",
    "marks": "Marks",
    "startLive": "Start Live",
    "sessionType": "Session Type",
    "chat": "Chat",
    "totalMarksObtained": "Total Marks Obtained",
    "call": "Call",
    "uploadStory": "Upload Story",
    "uploadYourPhoto": "Upload your photos",
    "customerSupport": "Astro Support",
    "chooseLanguage": "Choose Language",
    "priceChange": "Price Change",
    "numberChange": "Number Change",
    "reportAnAstrologer": "Report an Astrologer",
    "fAndQ": "F&Q",
    "offerType": "Offer Type",
    "firstFreeOffer": "FIRST FREE CONSULATION OFFER",
    "promotionOffer": "PROMOTION OFFER",
    "selectOffer": "Select Offer",
    "offerName": "Offer Name",
    "displayName": "Display Name",
    "userType": "User Type",
    "price": "Price",
    'divineShop': 'Divine Shop',
    "discountedPrice": "Discounted Price",
    'callAndChat': "Call & Chat",
    "status": "Status",
    "title": "Title",
    "endDate": "End Date",
    "selectEndDate": "Select End Date",
    "selectStartDate": "Select Start Date",
    "timePeriod": "Time Period",
    "toBeSettled": "to be settled",
    "nextOnlineTiming": "Next Online Timing",
    "follow": "Follow",
    "startDate": "Start Date",
    "selectCustomDate": "Select Custom Date",
    "astrologerId": "Astrologer Id",
    "profileOptions": "Profile Options",
    "profile": "Profile",
    "editProfile": "Edit Profile",
    "orderHistory": "Order History",
    "bankDetails": "Bank Details",
    "priceChangeRequest": "Price Change Request",
    "numberChangeRequest": "Number Change Request",
    "primaryPhoneNumber": "Primary Phone Number",
    "secondaryPhoneNumber": "Secondary Phone Number",
    "newPhoneNumber": "New Phone Number",
    "blockedUsers": "Blocked Users",
    "reportComment": "Report Comment",
    "chatAssistance": "Chat Assistance",
    "chatAssistanceHome": "     Chat\nAssistance",
    "suggestRemedy": "Suggest Remedy",
    "unblock": "Unblock",
    "performance": "Performance",
    "rankSystem": "Rank System",
    "availabilityTitle": "Today’s Availability (in mins)",
    "searchBlockUserHint": "Search For Blocked User",
    "ratings": "Ratings",
    "userReview": "User Review",
    "years": "Years",
    "date": "Date",
    "overallScore": "Overall Score",
    "update": "Update",
    "name": "Name",
    "rank": "Rank",
    "diamond": "Diamond",
    "busyChat": "Busy Chat",
    "busyCall": "Busy Call",
    "platinum": "Platinum",
    "busyHours": "Busy Hours",
    "gold": "Gold",
    "silver": "Silver",
    "liveHours": "Live Hours",
    "unranked": "Unranked",
    "conversionRate": "Conversion Rate",
    "repurchaseRate": "Repurchase Rate",
    "onlineHours": "Online Hours",
    "bronze": "Bronze",
    "availableChat": "Available Chat",
    "availableLive": "Available Live",
    "experience": "Experience",
    "availableCall": "Available Call",
    "approved": "Approved",
    "serviceType": "Service Type",
    "priceRequested": "Price Requested",
    "requestRaised": "Request Raised",
    "raiseTechnicalIssues": "Raise a Technical Issues",
    "priceChangeBtn": "Raise Request for New Price",
    "descriptions": "Descriptions",
    "speciality": "Speciality",
    "accountHolderName": "Account Holder Name",
    "bankAccountNumber": "Bank Account Number",
    "attachments": "Attachments",
    "iFSCCode": "IFSC Code",
    "yourBankDetails": "Your Bank Details",
    "customerPrice": "Customer Price",
    "numChangeMsgTitle": "You will get Call Chat alerts on these numbers.",
    "requestPriceChangeBtn": "Request Price Change",
    "hintTextName": "Please Enter Name",
    "holderNameHintText": "Please Enter Holder Name",
    "accountNumHintText": "Please Enter bank Account Number",
    "ifscCodeHintText": "Please Enter bank IFSC Code",
    "hintSpeciality": "Please Enter Speciality",
    "hintDescriptions": "Please Enter Descriptions",
    "hintExperience": "Please Enter Experience",
    "saveChanges": "Save Changes",
    "availableBalance": "Available \nBalance",
    "pgCharges": "PG \nCharges",
    "subTotal": "Sub\nTotal",
    "tds": "TDS ",
    "previous": "Previous",
    "percentage": "Percentage",
    "gotIt": "Got It",
    "next": "Next",
    "viewScore": "View Score",
    "close": "Close",
    "yourScore": "Your Score",
    "payAttention": "Pay Attention",
    "available": "Available",
    "changeAppLanguage": "Change app language",
    "astrologerRank": "Astrologer\nRank",
    "busy": "Busy",
    "deleteMyAccount": "Delete My Account",
    "logoutMyAccount": "Logout My Account",
    "termsAndConditions": "Terms And Conditions",
    "gst": "GST",
    "general": "General",
    "privacyPolicy": "Privacy Policy",
    "english": "English",
    "hindi": "Hindi",
    "marathi": "Marathi",
    "gujarati": "Gujarati",
    "totalAmount": "Total \nAmount",
    "referAnAstrologer": "Refer an Astrologer",
    "settings": "Settings",
    "profileUpdatedSuccessfully": "Profile updated successfully",
    "lastBillingCycle": "Last Billing Cycle",
    "amount": "Amount",
    "imageValidationMsg": "Image Can not be more than 5",
    "uploadImages": "Upload Images",
    "uploadYourPhotos": "Upload your photos",
    "contactUs": "Contact Us",
    "shareFeedback": "Share Feedback",
    "importantNumbers": "Important Numbers",
    "donation": "Donation",
    "importNumText":
        "You will get call and chat alerts from these numbers. Save these numbers to avoid any confusion.",
    "enterAmount": "Enter Amount",
    "enterCustomAmount": "Enter Custom Amount",
    "donateNow": "Donate Now",
    "customerCare": "Astro Care",
    "addContact": "Add Contact",
    "mobileNumber": "Mobile Number",
    "astrologySkill": "Astrology Skill",
    "platform": "Platform",
    "mandatoryFields": "Marked fields are Mandatory.",
    'personalDetails': 'Personal Details',
    "submitForm": "Submit Form",
    "nameEmptyValidation": "Name should not be empty",
    "waitlist": "Waitlist",
    "PlaceEmptyValidation": "Place should not be empty",
    "timeEmptyValidation": "Time should not be empty",
    "dateEmptyValidation": "Date should not be empty",
    "selectBirthPlace": "Select Birth Place",
    "addSpeciality": "Add Speciality",
    "astrologer": "Astrologer",
    "selectBirthTime": "Select Birth Time",
    "selectBirthDate": "Select Birth Date",
    "pleaseEnterYourName": "Please enter your name",
    "unreadMessages": "Unread Messages",
    "chatEnded": "This chat has been ended",
    "thankYouHelp": "Thank you for your help",
    "anotherPlatform": "Are they currently working on any other platform?",
    "enterNameMsg": "Enter Astrologer’s Name",
    "enterNumberMsg": "Enter Astrologer’s Mobile Number",
    "enterSkillsMsg": "Enter Astrologer’s Skill",
    "enterExperienceMsg": "Enter Astrologer’s Experience",
    "enterPlatformMsg": "Enter the platform they are working for",
    "yourEarning": "Your Earning",
    "lifeTimeEarning": "Life Time Earning",
    "totalEarning": "Total Earning",
    "selectVideo": "Select Video",
    "chatEarning": "Chat Earning",
    "callEarning": "Call Earning",
    "remediesLeft": "Remedies Left",
    "waitingQueue": "Waiting Queue",
    "nextInLine": "Next In Line",
    "reportEarning": "Report Earning",
    "suggestedRemediesEarning": "Suggested Remedies Earning",
    "help": "Help ",
    "poor": "Poor",
    "veryGood": "Very Good",
    "verify": "Verify",
    "enterRegisteredNumber": "Enter Registered Number",
    "mobileNumber10Digits": "Mobile number should be 10 digits.",
    "validPhoneNumber": "Please Enter Valid Phone Number.",
    "selectCountry": "Select a Country",
    "searchCountry": "Search a Country",
    "orderId": "Order Id",
    "dateTime": "Date Time",
    "giftName": "Gift Name",
    "giftPrice": "Gift Price",
    "quantity": "Quantity",
    "verificationHintText":
        "You will get a call on the number given above for verification",
    "gender": "Gender ",
    "dob": "DOB ",
    "pob": "POB ",
    "mobileNumberEmptyMsg": "Please enter mobile number.",
    "orderDateTime": "Order Date-Time ",
    "rate": "Rate ",
    "duration": "Duration : ",
    "priceChangeCondition": "Conditions for price change Request",
    "unBlockMsg":
        "If you unblock this user, then they’ll again be able to connect with you on the platform.",
    "refund": "Refund",
    "paymentGateway": "Payment Gateway",
    "totalTax": "Total Tax",
    "liveGifts": "Live Gifts",
    "remedySuggested": "Remedy suggested",
    "wallet": "Wallet",
    "all": "All",
    "suggest": "Suggest",
    "suggestRemedies": "Suggest Remedies",
    "daily": "Daily",
    "weekly": "Weekly",
    "monthly": "Monthly",
    "custom": "Custom",
    'deleteAccountMsg': 'Are you sure you want to delete your account ?',
    "aboutPooja": "About Pooja",
    "suggestNow": "Suggest Now",
    "clientPaid": "Client Paid",
    "okay": "Okay",
    "logout": "Logout",
    "signLord": "Sign Lord",
    "SignLord": "Sign\nLord",
    "starLord": "Star\nLord",
    "subLord": "Sub\nLord",
    "deleteAccount": "Delete Account",
    "logoutText": "Are you sure you want to logout ?",
    "deleteText": "Are you sure you want to delete your account ?",
    "home": "Home",
    "yes": "Yes",
    "sign": "Sign",
    "varna": "Varna",
    "nadi": "Nadi",
    "charan": "Charan",
    "noteText":
        "Note : The data will undergo regular refresh cycles with a frequency of once every",
    "tatva": "Tatva",
    "day": "Day",
    "sunrise": "Sunrise",
    "sunset": "Sunset",
    "karana": "Karana",
    "tithi": "Tithi",
    "yog": "Yog",
    "vashya": "Vashya",
    "nakshatra": "Nakshatra",
    "nakshatraLord": "Nakshatra Lord",
    "yoni": "Yoni",
    "no": "No",
    "confirm": "Confirm",
    "checkYours": "Check Yours",
    "checkOthers": "Check Others",
    "kundliText": "Kundli",
    "male": "Male",
    "female": "Female",
    "lagna": "Lagna",
    "moon": "Moon",
    "sun": "Sun",
    "gan": "Gan",
    "dosha": "Dosha",
    "birthPlace": "Birth Place",
    "prediction": "Prediction",
    "basicPanchang": "Basic Panchang",
    "navamansha": "Navamansha",
    "birthDetails": "Birth Details",
    "allFieldsText": "Please Fill All the Fields",
    "submit": "Submit",
    "passBook": "Passbook",
    "select": "Select",
    "cancelledCheque": "Cancelled Cheque",
    "birthTime": "Birth Time",
    "noResultFound": "No Result Found",
    "replyHere": "Reply here",
    "birthPalace": "Birth Palace",
    "confirmTimeBirth": "Confirm Time of Birth",
    "selectYourTimeBirth": "Select Your Time of Birth",
    "birthDate": "Birth Date",
    "jobTitle": "Great Job! No one is in wait list.",
    "confirmDateBirth": "Confirm Date of Birth",
    "selectYourDateBirth": "Select Your Date of Birth",
    "scheduleNow": "Schedule Now",
    "trainingVideos": "Training Videos",
    "videoCall": "Video Call",
    "feedbackHintText": "Type your feedback here!",
    "feedbacksText":
        "You are free to share your thoughts in order to help us improve.",
    "anyFeedbacks": "Any Feedbacks?",
    "eCommerce": "E-commerce",
    "addECommerce": "Add E-commerce",
    "submitFeedback": "Submit Feedback",
    "checkKundli": "Check Kundli",
    "chooseYourAppLanguage": "Choose Your App Language",
    "suggestRemediesHome": " Suggest \nRemedies",
    'scheduleOnlineTime': 'Schedule Your Next Online Time',
    'confirmOnlineTime': 'Confirm Next Online Time',
    'actualPayment': 'Actual Payment',
    'itSpam': 'It’s a spam',
    'ScheduleOnlineDate': 'Schedule Your Next Online Date',
    'nextOnlineTime': 'Next Online Time',
    'nextOnlineTimeDes':
        'Keep your users informed by setting your next online time here. This lets your clients know exactly when they can reach you again, ensuring they stay connected and can plan their consultations with ease.',
    'trainingVideoDes':
        "Our videos guide you through easy steps to enhance your performance. They're short, sweet, and packed with advice to help you earn more and make clients smile.",
    'confirmNextDate': 'Confirm Next Online Date',
    'hateSpeechSymbols': 'Hate speech or symbols',
    'violenceOrganisations': 'Violence or dangerous organisations',
    'falseInformation': 'False information',
    'scamFraud': 'Scam Fraud',
    'bullyingHarassment': 'Bullying harassment',
    'thankYouForReporting': 'Thank You For Reporting!',
    'thankYouDes':
        'We’ll review your report and necessary actions will be taken.',
    'bankName': 'Bank Name',
    'yogini': 'Yogini',
    'degree': 'Degree',
    'pitriDosha': 'Pitri Dosha',
    'sadesathiDosha': 'Sadesathi Dosha',
    'kalsarpDosha': 'Kalsarp Dosha',
    'manglikDosha': 'Manglik Dosha',
    'mahadasha': 'Mahadasha',
    'antarDasha': 'Antar Dasha',
    'pratyantarDasha': 'Pratyantar Dasha',
    'sookshmaDasha': 'Sookshma Dasha',
    'pranDasha': 'Pran Dasha',
    'noDataAntarDasha': 'No data found inside antar dasha',
    'noDataPratyantarDasha': 'No data found inside pratyantar dasha',
    'noDataSookshmaDasha': 'No data found inside sookshma dasha',
    'noDataPranDasha': 'No data found inside pran dasha',
    'bhadrika': 'Bhadrika',
    'rashiChart': 'Rashi Chart',
    'levelUp': 'Level Up',
    'physical': 'Physical',
    'character': 'Character',
    'health': 'Health',
    'sayHi': 'Say Hi',
    "astrologersLiveStar": "Astrologers's Live Star",
    'family': 'Family',
    'education': 'Education',
    'mahadashNote': 'The dates mentioned above are the ending dates.',
    'otpVerification': 'OTP Verification',
    'otpTextMsg': 'Enter the code from the sms we sent to',
    'notReceiveOTP': "Didn't receive OTP?",
    'resend': 'Resend',
    'noAttemptsLeft': 'No Attempts Left!',
    'attemptsRemaining': 'Attempts Remaining',
    'phoneNumberMustBe10Digit': 'Phone number must be 10 digit',
    'specialityNotEmpty': "Speciality can't be empty",
    'pleaseWait': 'Please wait...',
    'fromCalls': 'From Calls',
    'fromVideoCalls': 'From Video Calls',
    'fromPrivateCalls': 'From Private Calls',
    'fromLiveGifts': 'From Live Gifts',
    "YouHaveEarnedFromYourLastSession":
        "You've earned ₹@price from your last session",
    "YouHaveReceivedCalls": "You've received @count calls.",
    "YouHaveReceivedVideoCalls": "You've received @count video calls.",
    "YouHaveReceivedPrivateCalls": "You've received @count private calls.",
    "YouHaveReceivedLiveGifts": "You've received @count live gifts.",
    "isOnCall": "is on call",
    'orderDetails': 'Order Details',
    'orderType': 'Order Type',
    'walletBalance': 'Wallet Balance',
    'maximumOrderTime': 'Maximum Order Time',
    'specialty': 'Specialty',
    'languageProficiency': 'Language Proficiency',
    'astrologerRating': 'Astrologer Rating',
    'acceptChatRequest': 'Accept Chat Request',
    'sendNotificationImage': 'has send you an Image',
    'sendNotificationRemedy': 'has suggested you a remedy',
    'sendNotificationProduct': 'has suggested you a product',
    'sendNotificationGift': 'has send you an Gift',
    'sendNotificationFile': 'has send you a File',
    'sendNotificationLocation': 'has send you a Location',
    'addkundali': 'Add Kundli',
    'addKundaliText':
        'Fill in the details below to get the free personalized kundali',
    'hide': "Hide",
    'unHide': "Unhide",
    'eligibleBonus': 'You are Eligible for Bonus wallet!',
    'notEligibleBonus': 'You are Not Eligible for Bonus wallet!',
    'paidWallet': "Paid Wallet",
    'rePurchaseRate': "Repurchase Rate",
    'bonusWallet': "Bonus Wallet",
    'retentionRate': "Retention Rate",
    'ecommerceWallet': "Ecom. Wallet",
    'bonus': 'Bonus',
    'paid': 'Paid',
    'ecom': 'Ecom',
    'faq': "FAQ",
    'assistance': "Assistance",
    'queue': "Queue",
    'messageTemplate': "Message Template",
    'template': "Template",
    'clickToAdd': "+ Click here to add message template",
    'addTemplate': "Add Template",
    'enterTemplateName': "Enter Template Name",
    'enterDefaultMessage': "Enter Default Message",
    'updateForm': "Update Form",
    'underReview': "Under Review",
    'rejected': "Rejected",
    'userData': "User's Data",
    'users': "Users",
    'search': "Search",
    'sendMessage': "Send Message",
    'selectMessageToSend': "Select Message to Send",
    'noAnyTemplateFound': "No any template found",
    'liveLogs': "Live Logs",
    'noAnyDataFound': "No any data found",
    'liveDate': "Live Date",
    'totalLiveTime': "Total Live Time",
    'liveStartTime': "Live Start Time",
    'liveEndTime': "Live End Time",
    'tarotNCards': "Tarot\nCards",
    'product': "Product",
    'useTheseOptionsToSellECommerceProducts':
        "Use these options to sell e-commerce products.",
    'dailyLiveTimeRemaining_': "Daily Live Time Remaining -",
    'remainingMinutes': "Remaining Minutes",
    'weeksHoursRemaining': "Week’s Hours Remaining",
    'done': "Done",
    'minutes': "Minutes",
    'eligibleReward_': "Eligible Reward -",
    'faq': 'FAQ',
    'suggestAstrologer': 'Suggest Astrologer',
    'forYou': "For you",
    'availableAstrologers': 'Available Astrologers',
    'previousOrders': 'Previous Orders',
    'chatHistory': 'Chat History',
    'divineRemedies': 'Divine Remedies',
    'book': 'Book',
    'cashBack': 'Cash Back',
    'submitFeedBack': 'Submit Feedback',
    'stories': 'Stories',
    'offline': 'Offline',
    'viewChatHistory': 'View Chat History',
    'fromAstroChatCall':
        'Click chat/call, and you’ll get a chat/call from our astrologer\n(Wait Time',
    'minute': "minute",
    'yourAstrologer': 'Your Astrologer ',
    'asapAstrologer': 'Astrologer will connect you (ASAP)',
    'isWaitingChat': 'is Waiting for you on Chat',
    'willConnect': 'Will connect in',
    'reJoinChat': 'Re-Join Chat',
    'viewKundali': 'View Kundli',
    'personalizedKundali':
        "Fill in the details below to get free personalized kundli",
    'addYour': 'Add yours',
    'addOther': 'Add Others',
    'addedkundali': 'Added kundli',
    'askAstrologer': 'Ask a Astrologer',
    'simiarProduct': 'Similar Product',
    'astroDoubts': 'Doubts? Ask the astrologer if this product suits you!',
    'gstEighteen': 'Gst with 18%',
    'gstThree': 'Gst with 3%',
    'productSummary': 'Product Summary',
    'pooja': 'Pooja',
    'invoice': 'Invoice',
    'viewOrder': 'View Order',
    'viewCall': 'View Call',
    'viewChat': 'View Chat',
    'viewPooja': 'View Pooja',
    'facingIssue': 'Facing Login Issue?',
    'customerSupportMessage':
        'If you encounter any login-related problems,\n please reach out to our customer support team\n for assistance.',
    'customerText': 'Contact Customer Support',
    'trustMessage': 'India’s\nMost Trusted\nAstrology App',
    'loginOrSignUp': 'Log in or Sign up',
    'loginWithTrueCaller': 'Login with TrueCaller',
    'or': 'Or',
    'seconds': 'seconds',
    'enterOtp': 'Please Enter Correct OTP.',
    'trueCallerMessage':
        "Oops, seems like you're not logged-in in the TrueCaller App. Please ensure that you're logged-in in the TrueCaller App.",
    'resendIn': 'Resend in',
    'misMatchError': 'Time Mismatch Error!',
    'misMatchMessage':
        "Kindly review and synchronize your device's time settings to ensure accurate functionality.",
    'checkSetting': 'Check Settings',
    'recommendedMsg':
        'Please make sure you fill your form to save time for giving your personal details to the astrologer.',
    'recommendedTitle': 'Recommended',
    'emailText': "Email Id",
    'chat_with_astrologers': 'Chat with Astrologers',
    'call_with_astrologers': 'Call with Astrologers',
    'daily_stories': 'Daily Stories',
    'kundli_horoscope': 'Kundli & Horoscope',
    'previous_astro_search': 'Previously searched Astrologers',
    'explore_astrolgoers': 'Explore Astrologers',
    'my_astrologers': 'My Astrologers',
    'spell': 'Spell',
    'bracelets': 'Bracelets',
    'rudraksha': 'Rudraksha',
    'type_of_astrologer': 'What type of Astrologer you need?',
    'language': 'Language',
    'remedies': 'Remedies',
    'clear_filter': 'Clear Filters',
    'apply_filter': 'Apply Filters',
    'is_live_now': 'is live now',
    'show_less': 'Show Less',
    'show_more': 'Show More',
    'user_reviews': 'User Reviews',
    'gift': 'Gift',
    'father_name': 'Father name',
    'date_birth': 'Date of Birth',
    'city': 'City',
    'view_chat': 'View Chat',
    'chat_again': 'Chat again',
    'call_again': 'Call again',
    'products': 'Products',
    'e_commerce': 'E-Commerce',
    'sort_filter': 'Sort & Filter',
    'reset': 'Reset',
    'apply': 'Apply',
    'select_all': 'Select all',
    'clear': 'Clear',
    'pooja_main_category': 'Pooja Main Category',
    'booked_pooja': 'Booked Pooja',
    'pooja_sub_category': 'Pooja Sub Category',
    'starts_from': "Start's From",
    'about_the': "About the",
    'do_you_want_add_ons': "Do you want any add-ons?",
    'selected_add_ons': "Selected Add-Ons",
    'select_add_ons': "Select Add-Ons",
    'y_u_should_buy': "Why You should Buy from Us ?",
    'what_are_the_benefits': "What are the benefits?",
    'how_will_it_happen': "How will it happen?",
    'do_you_need_arrange_anything': "Do you need to arrange anything?",
    'suggested': "Suggested",
    'purchased': "Purchased",
    'have_coupon_code': "Have a coupon code?",
    'tap_here': "Tap Here!",
    'coupons_codes_for_you': "Coupon Codes For You",
    'best_coupons': "BEST COUPONS FOR YOU",
    'my_kundli': "My Kundli",
    'saved': "Saved",
    'kundli_detail': "Kundli Details",
    'planets_detail': "Planets Details",
    'view_profile': "View Profile",
    'based_on': "Based on",
    'special_remedies': "Special Remedies",
    'result': "Result",
    'add': "Add",
    'best_astrologer': "Best Astrologers",
    'based_on_your_need':
        "Based on your needs and requirements, the system will identify and recommend the most suitable astrologers available on the platform.",
    'do_good_deeds': "Do Good Deeds",
    'good_deeds_for': "Good deeds For",
    'cashback': "Cashback",
    'i_here_by_authorize':
        "I hereby authorize to receive RCS, Whatsapp messages and infomational emails.",
    'skip': "Skip",
    'stay': "Stay",
    'divine_discount': "Divine Discounts",
    'wallet_history': 'Wallet History',
    'top_up_helper': 'Top-up Helper',
    'deduction': 'Deduction',
    'gift_name': 'Gift Name',
    'gift_price': 'Gift Price',
    'by': 'By',
    'donated': 'Donated',
    'video': 'Video',
    'audio': 'Audio',
    'private': 'Private',
    'join': 'Join',
    'both_video_call': 'Both consultant and you on video call.',
    'both_audio_call': 'Consultant on video and you on audio.',
    'both_private_call':
        'Consultant on video, you on audio. No one can hear you, consultant is audible.',
    'would_like_follow': 'Would you like to follow.',
    'yes_follow': 'Yes, Follow',
    'wallet_balance': 'Wallet Balance',
    'please_select_city': 'Please select city',
    'search_birth_place': 'Search your birth place',
    'after_4_letters_city': 'Note :- After writing 4 letters you will get City',
    'select_your_country': 'Select Your Country',
    'love_matching': 'Love Matching',
    'select_birth_place': 'Select Birth Place',
    'chat_in_process': 'Chat in Progress',
    'media': 'Media',
    'end_chat': 'End Chat',
    'tell_us_experience': 'Tell us about your experience (optional)',
    'hide_name': 'Hide my name from all public reviews',
    'your_name_anonymous':
        'Your review will be public if you are not anonymous',
    'callAgain': 'Call Again',
    'searchPoojaShopOrders': 'Search pooja Orders',
    'chatAgain': 'Chat Again',
    'new_version_is_availble': 'New Version is Available!',
    'new_version_is_availble_text':
        'We recommend you to update your Divine App to the latest version to continue using the services.',
    'update_now': 'Update Now',
    'pass_book': 'Passbook',
    'what_is_bonus': 'What is Bonus Wallet ?',
    'what_is_ecommerce': 'What is Ecommerce Wallet ?',
    'what_is_paid': 'What is Paid Wallet ?',
    'suggestedRemedies': 'Suggested Remedies',
    'custom_product': 'Custom Product',
    'add_custom_product': 'Add Custom Product',
    'user_data': 'User Data',
    'click_to_connect_with_user':
        '(Click to connect with user and try to increase your Ecom on chat assistance)',
    'orders': 'Orders',
    'bySigning': 'By signing up, you agree to our ',
    'termsOfUse': 'terms of use',
    'sendOTP': 'Send OTP',
    'technical_support': 'Technical Support',
    'financial_support': 'Financial Support',
    'ecom_support': 'Ecom Support',
    'support': 'Support',
    'discount_offer': 'Discount Offers',
    'enter_dob': "Enter Astrologer's Date of Birth",
    'enter_father_name': "Enter Astrologer's Father Name",
    'enter_city': "Enter Astrologer's City",
    'please_make_sure_background_env':
        "Please make sure you and your background environment are ready to start a live check   your video and audio.",
    'to_guarantee_user_experience':
        "To guarantee the user experience, please make sure you can live for 30 mins at least.",
    'order_offers': "Order Offers",
    'product_name': "Product Name",
    'upload_product_image': "Upload Product Image",
    'product_price': "Product Price ( In INR )",
    'save': "Save",
    'warning_astrologers': "Warning Astrologer",
    'warning_text':
        "Your user retention is below industry standard. Your retention is less than 10% Your are not eligible for Bonus wallet. Please review and improve strategies promptly to increase User retention rate. Thank you. 🌟",
    'yourLevelRanks': "Your Level & Rank",
    'level': "Level",
    'user_retention_order': "User Retention ( Last 200 Orders )",
    'total_free_order': "Total Free Order",
    'converted_user': "Converted User",
    'retention': "Retention",
    'your_score': "Your Score",
    'out_of': "Out of",
    'click_here_to_know_criteria': "Click here to know the criteria",
    'ecom_type': "Ecom type",
    'categories': "Categories",
    'tags': "Tags",
    'select_tag': "Select tag",
    'select_puja_name': "Select puja name",
    'upload': "Upload",
    'image': "Image",
    'price_inr': "Price ( In INR )",
    'ticket_no': "Ticket No",
    'created': "Created",
    'ticket_type': "Ticket Type",
    'how_to_solve': "How to solve",
    'gifts': "Gifts",
    'order_feedbacks': "Order Feedbacks",
    'fines': "Fines",
    'type': "Type",
    'referral_bonus': "Referral Bonus",
    'nil': "Nil",
    'total_consulation': "Total Consultation",
    'last_consulted': "Last Consulted",
    'days_since_last_consulted': "Days Since Last Consulted",
    'connect': "Connect",
    'template_name': "Template Name",
    'template_message': "Template Message",
    'loadMoreReview': 'Load More Review',
    'select_skills': 'Select Skills',
    'current_tickets': 'Current Tickets',
    'submit_issue': 'Submit Issue',
    'please_explain_your_issue': 'Please explain your issue itn detail',
    'please_select_types': 'Please select Types',
    'please_provide_100_characters':
        'Please provide a more detailed description. (100 characters)',
    'all_issues': 'All Issues',
    'image_added': 'Images Added',
    'product_sold': 'Product\nSold',
    'BirthdateValidation': 'Please enter birth date',
    'pleaseEnterName': 'Please enter your name',
    'selectDateBirth': 'Select Your Date of Birth',
    'my_remedy': 'My Remedy',
    'tarot': 'Tarot',
    'kundli': 'Kundli',
    'check_kundli_details': 'Check Kundli Details',
  };
}
