Map<String, String> en() {
  return {
    "contactSaved": "Contact saved successfully",
    "Saved": "Saved",
    "errorLine1": "Something went wrong, please try again later",
    "contactPermissionRequired": "Contact permission is required",
    "noInternetConnection": "Please check your Internet connection",
    "internetSpeed": "Your Internet speed",
    "goodInternetConnection": "You Can Take Internet Calling",
    "badInternetConnection": "You Will Face Internet Call Issues.",
    "timeoutMessage":
        "Something went wrong.\nPlease check you internet connection and please try again.",
    "today": "Today",
    'deleteChat':'Delete Chat',
    "followers": "Followers",
    "dasha": "Dasha",
    "version": "Version",
    "somethingWentWrong": "Something went wrong",
    "total": "@count Total",
    'bhavChalitChart': 'Bhav Chalit Chart',
    "noticeBoard": "Notice board",
    "totalAvailability": "Total Availability",
    "last30Days": "Last 30 Days",
    "last30DaysDes": "This is your last 30 days availability. Where,'Available' is when you're online and waiting for clients, and 'Busy' is when you're talking to them in chats, calls, or live sessions.",
    "totalAvailabilityDes": "This is your current day availability. Where,'Available' is when you're online and waiting for clients, and 'Busy' is when you're talking to them in chats, calls, or live sessions.",
    "noticeBoardDes": "Here, you'll find essential information that keeps you connected and informed about what's new and what's next.",
    'cusps': 'Cusps',
    'cusp': 'Cusp',
    "viewAll": "View All",
    'planets': 'Planets',
    'rulingPlanets': 'Ruling Planets',
    'vimshottari': 'Vimshottari',
    "message": "Message",
    "senderCategory": "Sender Category",
    "readMore": "Read more",
    "kp": "KP",
    "reportingQue": "Why are you reporting this",
    "showLess": "Show less",
    "goLive": "Go Live",
    "live": "Live",
    "feedbackValidation": "Please Enter your feedback",
    "congratulations": "Congratulations",
    "tips": "Tips",
    "inMins": "in mins",
    "last30DaysAvailability": "Last 30 Days Availability",
    "marks": "Marks",
    "startLive": "Start Live",
    "sessionType": "Session Type",
    "chat": "Chat",
    "totalMarksObtained": "Total Marks Obtained",
    "call": "Call",
    "uploadStory": "Upload story",
    "uploadYourPhoto": "Upload your photo",
    "customerSupport": "Customer Support",
    "chooseLanguage": "Choose Language",
    "priceChange": "Price Change",
    "numberChange": "Number Change",
    "reportAnAstrologer": "Report an Astrologer",
    "fAndQ": "F&Q",
    "offerType": "Offer Type",
    "firstFreeOffer": "FIRST FREE CONSULATION OFFER",
    "promotionOffer": "PROMOTION OFFER",
    "selectOffer": "Select Offer",
    "offerName": "Offer Name",
    "displayName": "Display Name",
    "userType": "User Type",
    "price": "Price",
    'divineShop': 'Divine Shop',
    "discountedPrice": "Discounted Price",
    'callAndChat': "Call & Chat",
    "status": "Status",
    "title": "Title",
    "endDate": "End Date",
    "selectEndDate": "Select End Date",
    "selectStartDate": "Select Start Date",
    "timePeriod": "Time Period",
    "toBeSettled": "to be settled",
    "nextOnlineTiming": "Next Online Timing",
    "follow": "Follow",
    "startDate": "Start Date",
    "selectCustomDate": "Select Custom Date",
    "astrologerId": "Astrologer Id",
    "profileOptions": "Profile Options",
    "profile": "Profile",
    "editProfile": "Edit Profile",
    "orderHistory": "Order History",
    "bankDetails": "Bank Details",
    "priceChangeRequest": "Price Change Request",
    "numberChangeRequest": "Number Change Request",
    "primaryPhoneNumber": "Primary Phone Number",
    "secondaryPhoneNumber": "Secondary Phone Number",
    "newPhoneNumber": "New Phone Number",
    "blockedUsers": "Blocked Users",
    "reportComment": "Report Comment",
    "chatAssistance": "Chat Assistance",
    "chatAssistanceHome": "     Chat\nAssistance",
    "suggestRemedy": "Suggest Remedy",
    "unblock": "Unblock",
    "performance": "Performance",
    "rankSystem": "Rank System",
    "availabilityTitle": "Today’s Availability (in mins)",
    "searchBlockUserHint": "Search For Blocked User",
    "ratings": "Ratings",
    "userReview": "User Review",
    "years": "Years",
    "date": "Date",
    "overallScore": "Overall Score",
    "update": "Update",
    "name": "Name",
    "rank": "Rank",
    "diamond": "Diamond",
    "busyChat": "Busy Chat",
    "busyCall": "Busy Call",
    "platinum": "Platinum",
    "busyHours": "Busy Hours",
    "gold": "Gold",
    "silver": "Silver",
    "liveHours": "Live Hours",
    "unranked": "Unranked",
    "conversionRate": "Conversion Rate",
    "repurchaseRate": "Repurchase Rate",
    "onlineHours": "Online Hours",
    "bronze": "Bronze",
    "availableChat": "Available Chat",
    "availableLive": "Available Live",
    "experience": "Experience",
    "availableCall": "Available Call",
    "approved": "Approved",
    "serviceType": "Service Type",
    "priceRequested": "Price Requested",
    "requestRaised": "Request Raised",
    "raiseTechnicalIssues": "Raise a Technical Issues",
    "priceChangeBtn": "Raise Request for New Price",
    "descriptions": "Descriptions",
    "speciality": "Speciality",
    "accountHolderName": "Account Holder Name",
    "bankAccountNumber": "Bank Account Number",
    "attachments": "Attachments",
    "iFSCCode": "IFSC Code",
    "yourBankDetails": "Your Bank Details",
    "customerPrice": "Customer Price",
    "numChangeMsgTitle": "You will get Call Chat alerts on these numbers.",
    "requestPriceChangeBtn": "Request Price Change",
    "hintTextName": "Please Enter Name",
    "holderNameHintText": "Please Enter Holder Name",
    "accountNumHintText": "Please Enter bank Account Number",
    "ifscCodeHintText": "Please Enter bank IFSC Code",
    "hintSpeciality": "Please Enter Speciality",
    "hintDescriptions": "Please Enter Descriptions",
    "hintExperience": "Please Enter Experience",
    "saveChanges": "Save Changes",
    "availableBalance": "Available \nBalance",
    "pgCharges": "PG \nCharges",
    "subTotal": "Sub\nTotal",
    "tds": "TDS ",
    "previous": "Previous",
    "percentage": "Percentage",
    "gotIt": "Got It",
    "next": "Next",
    "viewScore": "View Score",
    "close": "Close",
    "yourScore": "Your Score",
    "payAttention": "Pay Attention",
    "available": "Available",
    "changeAppLanguage": "Change app language",
    "astrologerRank": "Astrologer\nRank",
    "busy": "Busy",
    "deleteMyAccount": "Delete My Account",
    "logoutMyAccount": "Logout My Account",
    "termsAndConditions": "Terms And Conditions",
    "gst": "GST",
    "general": "General",
    "privacyPolicy": "Privacy Policy",
    "english": "English",
    "hindi": "Hindi",
    "marathi": "Marathi",
    "gujarati": "Gujarati",
    "totalAmount": "Total \nAmount",
    "referAnAstrologer": "Refer an Astrologer",
    "settings": "Settings",
    "profileUpdatedSuccessfully": "Profile updated successfully",
    "lastBillingCycle": "Last Billing Cycle",
    "amount": "Amount",
    "imageValidationMsg": "Image Can not be more than 5",
    "uploadImages": "Upload Images",
    "uploadYourPhotos": "Upload your photos",
    "contactUs": "Contact Us",
    "shareFeedback": "Share Feedback",
    "importantNumbers": "Important Numbers",
    "donation": "Donation",
    "importNumText":
        "You will get call and chat alerts from these numbers. Save these numbers to avoid any confusion.",
    "enterAmount": "Enter Amount",
    "enterCustomAmount": "Enter Custom Amount",
    "donateNow": "Donate Now",
    "customerCare": "Customer Care",
    "addContact": "Add Contact",
    "mobileNumber": "Mobile Number",
    "astrologySkill": "Astrology Skill",
    "platform": "Platform",
    "mandatoryFields": "Marked fields are Mandatory.",
    'personalDetails': 'Personal Details',
    "submitForm": "Submit Form",
    "nameEmptyValidation": "Name should not be empty",
    "waitlist": "Waitlist",
    "PlaceEmptyValidation": "Place should not be empty",
    "timeEmptyValidation": "Time should not be empty",
    "dateEmptyValidation": "Date should not be empty",
    "selectBirthPlace": "Select Birth Place",
    "addSpeciality": "Add Speciality",
    "astrologer": "Astrologer",
    "selectBirthTime": "Select Birth Time",
    "selectBirthDate": "Select Birth Date",
    "pleaseEnterYourName": "Please enter your name",
    "unreadMessages": "Unread Messages",
    "chatEnded": "This chat has been ended",
    "thankYouHelp": "Thank you for your help",
    "anotherPlatform": "Are they currently working on any other platform?",
    "enterNameMsg": "Enter Astrologer’s Name",
    "enterNumberMsg": "Enter Astrologer’s Mobile Number",
    "enterSkillsMsg": "Enter Astrologer’s Skill",
    "enterExperienceMsg": "Enter Astrologer’s Experience",
    "enterPlatformMsg": "Enter the platform they are working for",
    "yourEarning": "Your Earning",
    "lifeTimeEarning": "Life Time Earning",
    "totalEarning": "Total Earning",
    "selectVideo": "Select Video",
    "chatEarning": "Chat Earning",
    "callEarning": "Call Earning",
    "remediesLeft": "Remedies Left",
    "waitingQueue": "Waiting Queue",
    "nextInLine": "Next In Line",
    "reportEarning": "Report Earning",
    "suggestedRemediesEarning": "Suggested Remedies Earning",
    "help": "Help ",
    "poor": "Poor",
    "veryGood": "Very Good",
    "verify": "Verify",
    "enterRegisteredNumber": "Enter Registered Number",
    "mobileNumber10Digits": "Mobile number should be 10 digits.",
    "validPhoneNumber": "Please Enter Valid Phone Number.",
    "selectCountry": "Select a Country",
    "searchCountry": "Search a Country",
    "orderId": "Order Id",
    "dateTime": "Date Time",
    "giftName": "Gift Name",
    "giftPrice": "Gift Price",
    "quantity": "Quantity",
    "verificationHintText":
        "You will get a call on the number given above for verification",
    "gender": "Gender ",
    "dob": "DOB ",
    "pob": "POB ",
    "mobileNumberEmptyMsg": "Please enter mobile number.",
    "orderDateTime": "Order Date-Time ",
    "rate": "Rate ",
    "duration": "Duration : ",
    "priceChangeCondition": "Conditions for price change Request",
    "unBlockMsg":
        "If you unblock this user, then they’ll again be able to connect with you on the platform.",
    "refund": "Refund",
    "paymentGateway": "Payment Gateway",
    "totalTax": "Total Tax",
    "liveGifts": "Live Gifts",
    "remedySuggested": "Remedy suggested",
    "wallet": "Wallet",
    "all": "All",
    "suggest": "Suggest",
    "suggestRemedies": "Suggest Remedies",
    "daily": "Daily",
    "weekly": "Weekly",
    "monthly": "Monthly",
    "custom": "Custom",
    'deleteAccountMsg': 'Are you sure you want to delete your account ?',
    "aboutPooja": "About Pooja",
    "suggestNow": "Suggest Now",
    "clientPaid": "Client Paid",
    "okay": "Okay",
    "logout": "Logout",
    "signLord": "Sign Lord",
    "SignLord": "Sign\nLord",
    "starLord": "Star\nLord",
    "subLord": "Sub\nLord",
    "deleteAccount": "Delete Account",
    "logoutText": "Are you sure you want to logout ?",
    "deleteText": "Are you sure you want to delete your account ?",
    "home": "Home",
    "yes": "Yes",
    "sign": "Sign",
    "varna": "Varna",
    "nadi": "Nadi",
    "charan": "Charan",
    "noteText":
        "Note : The data will undergo regular refresh cycles with a frequency of once every",
    "tatva": "Tatva",
    "day": "Day",
    "sunrise": "Sunrise",
    "sunset": "Sunset",
    "karana": "Karana",
    "tithi": "Tithi",
    "yog": "Yog",
    "vashya": "Vashya",
    "nakshatra": "Nakshatra",
    "nakshatraLord": "Nakshatra Lord",
    "yoni": "Yoni",
    "no": "No",
    "confirm": "Confirm",
    "checkYours": "Check Yours",
    "checkOthers": "Check Others",
    "kundliText": "Kundli",
    "male": "Male",
    "female": "Female",
    "lagna": "Lagna",
    "moon": "Moon",
    "sun": "Sun",
    "gan": "Gan",
    "dosha": "Dosha",
    "birthPlace": "Birth Place",
    "prediction": "Prediction",
    "basicPanchang": "Basic Panchang",
    "navamansha": "Navamansha",
    "birthDetails": "Birth Details",
    "allFieldsText": "Please Fill All the Fields",
    "submit": "Submit",
    "passBook": "Passbook",
    "select": "Select",
    "cancelledCheque": "Cancelled Cheque",
    "birthTime": "Birth Time",
    "noResultFound": "No Result Found",
    "replyHere": "Reply here",
    "birthPalace": "Birth Palace",
    "confirmTimeBirth": "Confirm Time of Birth",
    "selectYourTimeBirth": "Select Your Time of Birth",
    "birthDate": "Birth Date",
    "jobTitle": "Great Job! No one is in wait list.",
    "confirmDateBirth": "Confirm Date of Birth",
    "selectYourDateBirth": "Select Your Date of Birth",
    "scheduleNow": "Schedule Now",
    "trainingVideos": "Training Videos",
    "videoCall": "Video Call",
    "feedbackHintText": "Type your feedback here!",
    "feedbacksText":
        "You are free to share your thoughts in order to help us improve.",
    "anyFeedbacks": "Any Feedbacks?",
    "eCommerce": "E-commerce",
    "submitFeedback": "Submit Feedback",
    "checkKundli": "Check Kundli",
    "chooseYourAppLanguage": "Choose Your App Language",
    "suggestRemediesHome": " Suggest \nRemedies",
    'scheduleOnlineTime': 'Schedule Your Next Online Time',
    'confirmOnlineTime': 'Confirm Next Online Time',
    'actualPayment': 'Actual Payment',
    'itSpam': 'It’s a spam',
    'ScheduleOnlineDate': 'Schedule Your Next Online Date',
    'nextOnlineTime': 'Next Online Time',
    'nextOnlineTimeDes': 'Keep your users informed by setting your next online time here. This lets your clients know exactly when they can reach you again, ensuring they stay connected and can plan their consultations with ease.',
    'trainingVideoDes': "Our videos guide you through easy steps to enhance your performance. They're short, sweet, and packed with advice to help you earn more and make clients smile.",
    'confirmNextDate': 'Confirm Next Online Date',
    'hateSpeechSymbols': 'Hate speech or symbols',
    'violenceOrganisations': 'Violence or dangerous organisations',
    'falseInformation': 'False information',
    'scamFraud': 'Scam Fraud',
    'bullyingHarassment': 'Bullying harassment',
    'thankYouForReporting': 'Thank You For Reporting!',
    'thankYouDes':
        'We’ll review your report and necessary actions will be taken.',
    'bankName': 'Bank Name',
    'yogini': 'Yogini',
    'degree': 'Degree',
    'pitriDosha': 'Pitri Dosha',
    'sadesathiDosha': 'Sadesathi Dosha',
    'kalsarpDosha': 'Kalsarp Dosha',
    'manglikDosha': 'Manglik Dosha',
    'mahadasha': 'Mahadasha',
    'antarDasha': 'Antar Dasha',
    'pratyantarDasha': 'Pratyantar Dasha',
    'sookshmaDasha': 'Sookshma Dasha',
    'pranDasha': 'Pran Dasha',
    'noDataAntarDasha': 'No data found inside antar dasha',
    'noDataPratyantarDasha': 'No data found inside pratyantar dasha',
    'noDataSookshmaDasha': 'No data found inside sookshma dasha',
    'noDataPranDasha': 'No data found inside pran dasha',
    'bhadrika': 'Bhadrika',
    'rashiChart': 'Rashi Chart',
    'levelUp': 'Level Up',
    'physical': 'Physical',
    'character': 'Character',
    'health': 'Health',
    'sayHi': 'Say Hi',
    "astrologersLiveStar": "Astrologers's Live Star",
    'family': 'Family',
    'education': 'Education',
    'mahadashNote': 'The dates mentioned above are the ending dates.',
    'otpVerification': 'OTP Verification',
    'otpTextMsg': 'Enter the code from the sms we sent to',
    'notReceiveOTP': "Didn't receive OTP?",
    'resend': 'Resend',
    'noAttemptsLeft': 'No Attempts Left!',
    'attemptsRemaining': 'Attempts Remaining',
    'phoneNumberMustBe10Digit': 'Phone number must be 10 digit',
    'specialityNotEmpty': "Speciality can't be empty",
    'pleaseWait': 'Please wait...',
    'fromCalls': 'From Calls',
    'fromVideoCalls': 'From Video Calls',
    'fromPrivateCalls': 'From Private Calls',
    'fromLiveGifts': 'From Live Gifts',
    "YouHaveEarnedFromYourLastSession":
        "You've earned ₹@price from your last session",
    "YouHaveReceivedCalls": "You've received @count calls.",
    "YouHaveReceivedVideoCalls": "You've received @count video calls.",
    "YouHaveReceivedPrivateCalls": "You've received @count private calls.",
    "YouHaveReceivedLiveGifts": "You've received @count live gifts.",
    "isOnCall": "is on call",
    'orderDetails': 'Order Details',
    'orderType': 'Order Type',
    'walletBalance': 'Wallet Balance',
    'maximumOrderTime': 'Maximum Order Time',
    'specialty': 'Specialty',
    'languageProficiency': 'Language Proficiency',
    'astrologerRating': 'Astrologer Rating',
    'acceptChatRequest': 'Accept Chat Request',
  'sendNotificationImage': 'has send you an Image',
  'sendNotificationRemedy': 'has suggested you a remedy',
  'sendNotificationProduct': 'has suggested you a product',
  'sendNotificationGift': 'has send you an Gift',
  'sendNotificationFile': 'has send you a File',
  'sendNotificationLocation': 'has send you a Location',
  };
}
