Map<String, String> en() {
  return {

  "noInternetConnection" : "Please check your Internet connection",
  "timeoutMessage": "Something went wrong.\nPlease check you internet connection and please try again.",
  "today" : "Today",
  "followers" : "Followers",
  "total" : "Total",
  "noticeBoard" : "Notice board",
  "viewAll" : "View All",
  "message" : "Message",
  "senderCategory" : "Sender Category",
  "readMore" : "Read more",
  "showLess" : "Show less",
  "goLive" : "Go Live",
  "live" : "Live",
  "congratulations" : "Congratulations",
  "tips" : "Tips",
  "startLive" : "Start Live",
  "sessionType" : "Session Type",
  "chat" : "Chat",
  "totalMarksObtained" : "Total Marks Obtained",
  "call" : "Call",
  "uploadStory" : "Upload story",
  "uploadYourPhoto" : "Upload your photo",
  "customerSupport" : "Customer Support",
  "chooseLanguage" : "Choose Language",
  "priceChange" : "Price Change",
  "numberChange" : "Number Change",
  "reportAnAstrologer" : "Report an Astrologer",
  "fAndQ" : "F&Q",
  "offerType" : "Offer Type",
  "firstFreeOffer" : "FIRST FREE CONSULATION OFFER",
  "promotionOffer" : "PROMOTION OFFER",
  "status" : "Status",
  "nextOnlineTiming" : "Next Online Timing",
  "follow" : "Follow",
  "customerId" : "Customer Id",
  "profileOptions" : "Profile Options",
  "profile" : "Profile",
  "editProfile" : "Edit Profile",
  "orderHistory" : "Order History",
  "bankDetails" : "Bank Details",
  "priceChangeRequest" : "Price Change Request",
  "numberChangeRequest" : "Number Change Request",
  "primaryPhoneNumber" : "Primary Phone Number",
  "secondaryPhoneNumber" : "Secondary Phone Number",
  "blockedUsers" : "Blocked Users",
  "reportComment" : "Report Comment",
  "chatAssistance" : "Chat Assistance",
  "suggestRemedy" : "Suggest Remedy",
  "unblock" : "Unblock",
  "performance" : "Performance",
  "rankSystem" : "Rank System",
  "availabilityTitle" : "Today’s Availability (in mins)",
  "searchBlockUserHint" : "Search For Blocked User",
  "ratings" : "Ratings",
  "userReview" : "User Review",
  "years" : "Years",
  "date" : "Date",
  "overallScore" : "Overall Score",
  "update" : "Update",
  "name" : "Name",
  "rank" : "Rank",
  "diamond" : "Diamond",
  "busyChat" : "Busy Chat",
  "busyCall" : "Busy Call",
  "platinum" : "Platinum",
  "busyHours" : "Busy Hours",
  "gold" : "Gold",
  "silver" : "Silver",
  "liveHours" : "Live Hours",
  "unranked" : "Unranked",
  "conversionRate" : "Conversion Rate",
  "repurchaseRate" : "Repurchase Rate",
  "onlineHours" : "Online Hours",
  "bronze" : "Bronze",
  "availableChat" : "Available Chat",
  "availableLive" : "Available Live",
  "experience" : "Experience",
  "availableCall" : "Available Call",
  "approved" : "Approved",
  "serviceType" : "Service Type",
  "priceRequested" : "Price Requested",
  "requestRaised" : "Request Raised",
  "priceChangeBtn" : "Raise Request for New Price",
  "descriptions" : "Descriptions",
  "speciality" : "Speciality",
  "accountHolderName" : "Account Holder Name",
  "bankAccountNumber" : "Bank Account Number",
  "attachments" : "Attachments",
  "iFSCCode" : "IFSC Code",
  "yourBankDetails" : "Your Bank Details",
  "customerPrice" : "Customer Price",
  "numChangeMsgTitle" : "You will get Call Chat alerts on these numbers.",
  "requestPriceChangeBtn" : "Request Price Change",
  "hintTextName" : "Please Enter Name",
  "holderNameHintText" : "Please Enter Holder Name",
  "accountNumHintText" : "Please Enter bank Account Number",
  "ifscCodeHintText" : "Please Enter bank IFSC Code",
  "hintSpeciality" : "Please Enter Speciality",
  "hintDescriptions" : "Please Enter Descriptions",
  "hintExperience" : "Please Enter Experience",
  "saveChanges" : "Save Changes",
  "availableBalance" : "Available \nBalance",
  "pgCharges" : "PG \nCharges",
  "subTotal" : "Sub\nTotal",
  "tds" : "TDS ",
  "available" : "Available",
  "changeAppLanguage" : "Change app language",
  "astrologerRank" : "Astrologer Rank",
  "busy" : "Busy",
  "deleteMyAccount" : "Delete My Account",
  "logoutMyAccount" : "Logout My Account",
  "termsAndConditions" : "Terms And Conditions",
  "gst" : "GST",
  "general" : "General",
  "privacyPolicy" : "Privacy Policy",
  "english" : "English",
  "totalAmount" : "Total \nAmount",
  "referAnAstrologer" : "Refer an Astrologer",
  "settings" : "Settings",
  "contactUs" : "Contact Us",
  "shareFeedback" : "Share Feedback",
  "importantNumbers" : "Important numbers",
  "donation" : "Donation",
  "addContact" : "Add Contact",
  "mobileNumber" : "Mobile Number",
  "astrologySkill" : "Astrology Skill",
  "platform" : "Platform",
  "mandatoryFields" : "Marked fields are Mandatory.",
  "submitForm" : "Submit Form",
  "waitlist" : "Waitlist",
  "anotherPlatform" : "Are they currently working on any other platform?",
  "enterNameMsg" : "Enter Astrologer’s Name",
  "enterNumberMsg" : "Enter Astrologer’s Mobile Number",
  "enterSkillsMsg" : "Enter Astrologer’s Skill",
  "enterExperienceMsg" : "Enter Astrologer’s Experience",
  "enterPlatformMsg" : "Enter the platform they are working for",
  "yourEarning" : "Your Earning",
  "lifeTimeEarning" : "Life Time Earning",
  "totalEarning" : "Total Earning",
  "chatEarning" : "Chat Earning",
  "callEarning" : "Call Earning",
  "remediesLeft" : "Remedies Left",
  "waitingQueue" : "Waiting Queue",
  "nextInLine" : "Next In Line",
  "reportEarning" : "Report Earning",
  "suggestedRemediesEarning" : "Suggested Remedies Earning",
  "help" : "Help ",
  "orderId" : "Order Id  ",
  "gender" : "Gender ",
  "dob" : "DOB ",
  "pob" : "POB ",
  "orderDateTime" : "Order Date-Time ",
  "rate" : "Rate ",
  "duration" : "Duration : ",
  "priceChangeCondition" : "Conditions for price change Request",
  "unBlockMsg" : "If you unblock this user, then they’ll again be able to connect with you on the platform.",
  "refund" : "Refund",
  "liveGifts" : "Live Gifts",
  "remedySuggested" : "Remedy suggested",
  "wallet" : "Wallet",
  "all" : "All",
  "suggest" : "Suggest",
  "suggestRemedies" : "Suggest Remedies",
  "daily" : "Daily",
  "weekly" : "Weekly",
  "monthly" : "Monthly",
  "custom" : "Custom",
  "aboutPooja" : "About Pooja",
  "suggestNow" : "Suggest Now",
  "clientPaid" : "Client Paid",
  "okay" : "Okay",
  "logout" : "Logout",
  "deleteAccount" : "Delete Account",
  "logoutText" : "Are you sure you want to logout ?",
  "deleteText" : "Are you sure you want to delete your account ?",
  "home" : "Home",
  "yes" : "Yes",
  "sign" : "Sign",
  "varna" : "Varna",
  "nadi" : "Nadi",
  "charan" : "Charan",
  "noteText" : "Note : The data will undergo regular refresh cycles with a frequency of once every",
  "tatva" : "Tatva",
  "day" : "Day",
  "sunrise" : "Sunrise",
  "sunset" : "Sunset",
  "karana" : "Karana",
  "tithi" : "Tithi",
  "yog" : "Yog",
  "vashya" : "Vashya",
  "nakshatra" : "Nakshatra",
  "nakshatraLord" : "Nakshatra Lord",
  "yoni" : "Yoni",
  "no" : "No",
  "checkYours" : "Check Yours",
  "checkOthers" : "Check Others",
  "kundliText" : "Kundli",
  "male" : "Male",
  "female" : "Female",
  "lagna" : "Lagna",
  "moon" : "Moon",
  "sun" : "Sun",
  "gan" : "Gan",
  "signLord" : "સહી પ્રભુ",
  "dosha" : "Dosha",
  "birthPlace" : "Birth Place",
  "prediction" : "Prediction",
  "basicPanchang" : "Basic Panchang",
  "navamansha" : "Navamansha",
  "birthDetails" : "Birth Details",
  "allFieldsText" : "Please Fill All the Fields",
  "submit" : "Submit",
  "birthTime" : "Birth Time",
  "birthPalace" : "Birth Palace",
  "confirmTimeBirth" : "Confirm Time of Birth",
  "selectYourTimeBirth" : "Select Your Time of Birth",
  "birthDate" : "Birth Date",
  "confirmDateBirth" : "Confirm Date of Birth",
  "selectYourDateBirth" : "Select Your Date of Birth",
  "scheduleNow" : "Schedule Now",
  "trainingVideos" : "Training Videos",
  "feedbackHintText" : "Type your feedback here!",
  "feedbacksText" : "You are free to share your thoughts in order to help us improve.",
  "anyFeedbacks" : "Any Feedbacks?",
  "eCommerce" : "E-commerce",
  "submitFeedback" : "Submit Feedback",
  "checkKundli" : "Check Kundli",
  "chooseYourAppLanguage" : "Choose Your App Language",
  "suggestRemediesHome" : " Suggest \nRemedies",

};
}
