Map<String, String> gu() {
  return {
    "noInternetConnection": "કૃપા કરીને તમારું ઇન્ટરનેટ કનેક્શન તપાસો",
    "timeoutMessage":
        "કંઈક ખોટું થયું.\nકૃપા કરીને તમારું ઇન્ટરનેટ કનેક્શન તપાસો અને કૃપા કરીને ફરી પ્રયાસ કરો.",
    "today": "આજે",
    "followers": "અનુયાયીઓ",
    "total": "કુલ",
    "noticeBoard": "સૂચના બોર્ડ",
    "viewAll": "બધુજ જુઓ",
    "message": "સંદેશ",
    "senderCategory": "પ્રેષક શ્રેણી",
    "readMore": "વધુ વાંચો",
    "showLess": "ઓછું બતાવો",
    "uploadStory" : "વાર્તા અપલોડ કરો",
    "uploadYourPhoto" : "તમારો ફોટો અપલોડ કરો",
    "customerSupport" : "ગ્રાહક સેવા",
    "chooseLanguage" : "ભાષા પસંદ કરો",
    "fAndQ" : "F&Q",
    "priceChange" : "ભાવ ફેરફાર",
    "numberChange" : "નંબર ચેન્જ",
    "reportAnAstrologer" : "જ્યોતિષની જાણ કરો",
    "goLive": "લાઈવ જાઓ",
    "live": "લાઈવ",
    "congratulations": "અભિનંદન",
    "tips": "ટિપ્સ",
    "startLive": "લાઈવ શરૂ કરો",
    "sessionType": "સત્રનો પ્રકાર",
    "chat": "ચેટ",
    "totalMarksObtained": "કુલ ગુણ મેળવ્યા",
    "call": "કૉલ કરો",
    "offerType": "ઓફર પ્રકાર",
    "firstFreeOffer": "પ્રથમ મફત કન્સ્યુલેશન ઓફર",
    "promotionOffer": "પ્રમોશન ઑફર",
    "status": "સ્થિતિ",
    "nextOnlineTiming": "આગામી ઓનલાઇન સમય",
    "follow": "અનુસરો",
    "customerId": "ગ્રાહક ઓળખાણ પત્ર",
    "profileOptions": "પ્રોફાઇલ વિકલ્પો",
    "profile": "પ્રોફાઇલ",
    "editProfile": "પ્રોફાઇલ સંપાદિત કરો",
    "orderHistory": "ઓર્ડર ઇતિહાસ",
    "bankDetails": "બેંકની વિગત",
    "priceChangeRequest": "ભાવ બદલવાની વિનંતી",
    "numberChangeRequest": "નંબર બદલવાની વિનંતી",
    "primaryPhoneNumber": "પ્રાથમિક ફોન નંબર",
    "secondaryPhoneNumber": "ગૌણ ફોન નંબર",
    "blockedUsers": "અવરોધિત વપરાશકર્તાઓ",
    "reportComment": "ટિપ્પણીની જાણ કરો",
    "chatAssistance": "ચેટ સહાય",
    "suggestRemedy": "ઉપાય સૂચવો",
    "unblock": "અનાવરોધિત કરો",
    "performance": "પ્રદર્શન",
    "rankSystem": "રેન્ક સિસ્ટમ",
    "availabilityTitle": "આજની ઉપલબ્ધતા (મિનિટમાં)",
    "searchBlockUserHint": "અવરોધિત વપરાશકર્તા માટે શોધો",
    "ratings": "રેટિંગ્સ",
    "userReview": "વપરાશકર્તા સમીક્ષા",
    "years": "વર્ષ",
    "date": "તારીખ",
    "overallScore": "કુલ આંક",
    "update": "અપડેટ કરો",
    "name": "નામ",
    "rank": "ક્રમ",
    "diamond": "હીરા",
    "busyChat": "વ્યસ્ત ચેટ",
    "busyCall": "વ્યસ્ત કૉલ",
    "availableChat": "ઉપલબ્ધ ચેટ",
    "availableLive": "ઉપલબ્ધ લાઈવ",
    "experience": "અનુભવ",
    "availableCall": "ઉપલબ્ધ કૉલ",
    "approved": "મંજૂર",
    "serviceType": "સેવાનો પ્રકાર",
    "priceRequested": "કિંમતની વિનંતી કરી",
    "requestRaised": "વિનંતી ઉઠાવી",
    "priceChangeBtn": "નવી કિંમત માટે વિનંતી વધારો",
    "descriptions": "વર્ણનો",
    "speciality": "વિશેષતા",
    "accountHolderName": "એકાઉન્ટ ધારકનું નામ",
    "bankAccountNumber": "બેંક એકાઉન્ટ નંબર",
    "attachments": "જોડાણો",
    "iFSCCode": "IFSC કોડ",
    "yourBankDetails": "તમારી બેંક વિગતો",
    "customerPrice": "ગ્રાહક ભાવ",
    "numChangeMsgTitle": "તમને આ નંબરો પર કોલ ચેટ એલર્ટ મળશે.",
    "requestPriceChangeBtn": "ભાવમાં ફેરફારની વિનંતી કરો",
    "hintTextName": "કૃપા કરીને નામ દાખલ કરો",
    "holderNameHintText": "કૃપા કરીને ધારકનું નામ દાખલ કરો",
    "accountNumHintText": "કૃપા કરીને બેંક એકાઉન્ટ નંબર દાખલ કરો",
    "ifscCodeHintText": "કૃપા કરીને બેંકનો IFSC કોડ દાખલ કરો",
    "hintSpeciality": "કૃપા કરીને વિશેષતા દાખલ કરો",
    "hintDescriptions": "કૃપા કરીને વર્ણનો દાખલ કરો",
    "hintExperience": "કૃપા કરીને અનુભવ દાખલ કરો",
    "saveChanges": "ફેરફારો સંગ્રહ",
    "availableBalance": "ઉપલબ્ધ \nબેલેન્સ",
    "pgCharges": "PG \nચાર્જ",
    "subTotal": "પેટા\nકુલ",
    "tds": "ટીડીએસ: ",
    "available": "ઉપલબ્ધ છે",
    "changeAppLanguage": "એપ્લિકેશન ભાષા બદલો",
    "astrologerRank": "જ્યોતિષ રેન્ક",
    "busy": "વ્યસ્ત",
    "deleteMyAccount": "મારું એકાઉન્ટ કાઢી નાખો",
    "logoutMyAccount": "મારું એકાઉન્ટ લોગઆઉટ કરો",
    "termsAndConditions": "નિયમો અને શરત",
    "gst": "GST:",
    "general": "જનરલ",
    "privacyPolicy": "ગોપનીયતા નીતિ",
    "english": "અંગ્રેજી",
    "totalAmount": "કુલ \nરકમ",
    "referAnAstrologer": "જ્યોતિષ નો સંદર્ભ લો",
    "settings": "સેટિંગ્સ",
    "contactUs": "અમારો સંપર્ક કરો",
    "shareFeedback": "પ્રતિસાદ શેર કરો",
    "importantNumbers": "મહત્વપૂર્ણ સંખ્યાઓ",
    "donation": "દાન:",
    "addContact": "સંપર્ક ઉમેરો",
    "mobileNumber": "મોબાઇલ નંબર",
    "astrologySkill": "જ્યોતિષ કૌશલ્ય",
    "platform": "પ્લેટફોર્મ",
    "mandatoryFields": "ચિહ્નિત ક્ષેત્રો ફરજિયાત છે.",
    "submitForm": "ફોર્મ સબમિટ કરો",
    "waitlist": "વેઇટલિસ્ટ",
    "anotherPlatform": "શું તેઓ હાલમાં અન્ય કોઈ પ્લેટફોર્મ પર કામ કરે છે?",
    "enterNameMsg": "જ્યોતિષનું નામ દાખલ કરો",
    "enterNumberMsg": "જ્યોતિષીનો મોબાઈલ નંબર દાખલ કરો",
    "enterSkillsMsg": "જ્યોતિષની કૌશલ્ય દાખલ કરો",
    "enterExperienceMsg": "જ્યોતિષીનો અનુભવ દાખલ કરો",
    "enterPlatformMsg": "તેઓ જે પ્લેટફોર્મ માટે કામ કરી રહ્યા છે તે દાખલ કરો",
    "yourEarning": "તમારી કમાણી",
    "lifeTimeEarning": "જીવન સમયની કમાણી",
    "totalEarning": "કુલ કમાણી",
    "chatEarning": "ચેટ કમાણી",
    "callEarning": "કૉલ અર્નિંગ",
    "remediesLeft": "બાકી ઉપાયો",
    "waitingQueue": "રાહ જોવાની કતાર",
    "nextInLine": "લાઇનમાં આગળ",
    "reportEarning": "રિપોર્ટ અર્નિંગ",
    "suggestedRemediesEarning": "સૂચવેલા ઉપાયો કમાણી",
    "help": "મદદ ",
    "orderId": "ઓર્ડર આઈડી  ",
    "gender": "જાતિ ",
    "dob": "ડીઓબી ",
    "pob": "પીઓબી ",
    "orderDateTime": "ઓર્ડર તારીખ-સમય ",
    "rate": "દર : ",
    "duration": "અવધિ : ",
    "priceChangeCondition": "ભાવ ફેરફાર વિનંતી માટે શરતો",
    "unBlockMsg":
        "જો તમે આ વપરાશકર્તાને અનાવરોધિત કરો છો, તો તેઓ ફરીથી તમારી સાથે પ્લેટફોર્મ પર કનેક્ટ થઈ શકશે.",
    "refund": "પરત કરેલી રકમ",
    "liveGifts": "જીવંત ભેટો",
    "remedySuggested": "ઉપાય સૂચવ્યો",
    "wallet": "વૉલેટ",
    "all": "બધા",
    "suggest": "સૂચન કરો",
    "suggestRemedies": "ઉપાયો સૂચવો",
    "daily" : "દૈનિક",
    "weekly" : "સાપ્તાહિક",
    "monthly" : "માસિક",
    "custom" : "કસ્ટમ",
    "aboutPooja" : "પૂજા વિશે",
    "suggestNow" : "હવે સૂચવો",
    "clientPaid" : "ગ્રાહક ચૂકવેલ",
    "okay" : "બરાબર",
    "home" : "ઘર",
    "logout" : "લૉગ આઉટ",
    "deleteAccount" : "એકાઉન્ટ કાઢી નાખો",
    "deleteText" : "શું તમે ખરેખર તમારું એકાઉન્ટ કાઢી નાખવા માંગો છો?",
    "logoutText" : "શું તમે ખરેખર લોગઆઉટ કરવા માંગો છો?",
    "submitFeedback" : "પ્રતિસાદ સબમિટ કરો",
    "feedbackHintText" : "તમારો પ્રતિસાદ અહીં લખો!",
    "feedbacksText" : "અમને સુધારવામાં મદદ કરવા માટે તમે તમારા વિચારો શેર કરવા માટે મુક્ત છો.",
    "anyFeedbacks" : "કોઈ પ્રતિસાદ?",
    "eCommerce" : "ઈ-કોમર્સ",
    "scheduleNow" : "હવે સુનિશ્ચિત કરો",
    "yes" : "હા",
    "no" : "ના",
    "vashya" : "વશ્ય",
    "nadi" : "નાડી",
    "charan" : "ચરણ",
    "tatva" : "તત્વ",
    "sign" : "હસ્તાક્ષર",
    "yoni" : "યોની",
    "varna" : "વર્ણા",
    "nakshatra" : "નક્ષત્ર",
    "nakshatraLord" : "નક્ષત્ર ભગવાન",
    "checkYours" : "તમારી તપાસ કરો",
    "checkOthers" : "અન્ય તપાસો",
    "kundliText" : "કુંડલી",
    "male" : "પુરુષ",
    "busyHours" : "વ્યસ્ત કલાકો",
    "liveHours" : "લાઈવ અવર્સ",
    "day" : "દિવસ",
    "yog" : "યોગ",
    "onlineHours" : "ઑનલાઇન કલાકો",
    "sunrise" : "સૂર્યોદય",
    "conversionRate" : "રૂપાંતરણ દર",
    "repurchaseRate" : "પુનઃખરીદી દર",
    "unranked" : "અન ક્રમાંકિત",
    "bronze" : "કાંસ્ય",
    "sunset" : "સૂર્યાસ્ત",
    "silver" : "ચાંદીના",
    "gold" : "સોનું",
    "tithi" : "તિથિ",
    "lagna" : "લગના",
    "karana" : "કરણા",
    "platinum" : "પ્લેટિનમ",
    "noteText" : "નોંધ : ડેટા દર એક વખતની આવર્તન સાથે નિયમિત રીફ્રેશ ચક્રમાંથી પસાર થશે",
    "moon" : "ચંદ્ર",
    "sun" : "સૂર્ય",
    "dosha" : "દોષ",
    "gan" : "ગણ",
    "signLord" : "સાઇન લોર્ડ",
    "prediction" : "આગાહી",
    "birthPlace" : "જન્મસ્થળ",
    "basicPanchang" : "મૂળભૂત પંચાંગ",
    "navamansha" : "નવમાંશા",
    "submit" : "સબમિટ કરો",
    "birthDetails" : "જન્મની વિગતો",
    "allFieldsText" : "કૃપા કરીને તમામ ક્ષેત્રો ભરો",
    "birthDate" : "જન્મતારીખ",
    "birthTime" : "જન્મ સમય",
    "birthPalace" : "જન્મ મહેલ",
    "confirmTimeBirth" : "જન્મ સમયની પુષ્ટિ કરો",
    "selectYourTimeBirth" : "તમારો જન્મ સમય પસંદ કરો",
    "confirmDateBirth" : "જન્મ તારીખની પુષ્ટિ કરો",
    "selectYourDateBirth" : "તમારી જન્મ તારીખ પસંદ કરો",
    "female" : "સ્ત્રી",
    "trainingVideos" : "તાલીમ વિડિઓઝ",
    "checkKundli" : "કુંડળી તપાસો",
    "suggestRemediesHome" : "ઉપાયો\nસૂચવો",
    "chooseYourAppLanguage" : "તમારી એપ્લિકેશન ભાષા પસંદ કરો",
    "payAttention" : "ધ્યાન આપો",
    "yourScore" : "તમારો સ્કોર",
    "previous" : "અગાઉના",
    "next" : "આગળ",
    "close" : "બંધ",
    "viewScore" : "સ્કોર જુઓ",
    "gotIt" : "જાણ્યું",
    'itSpam': 'તે સ્પામ છે',
    'hateSpeechSymbols': 'અપ્રિય ભાષણ અથવા પ્રતીકો',
    'violenceOrganisations': 'હિંસા અથવા ખતરનાક સંસ્થાઓ',
    'falseInformation': 'ખોટી માહિતી',
    'scamFraud': 'સ્કેમ ફ્રોડ',
    'bullyingHarassment': 'પજવણી',
    'thankYouForReporting': 'જાણ કરવા બદલ આભાર!',
    'thankYouDes': 'અમે તમારા રિપોર્ટની સમીક્ષા કરીશું અને જરૂરી પગલાં લેવામાં આવશે.',

  };
}
