Map<String, String> hi() {
  return {
    "noInternetConnection": "कृपया अपने इंटरनेट कनेक्शन की जाँच करें",
    "timeoutMessage":
        "कुछ गलत हो गया।\nकृपया अपना इंटरनेट कनेक्शन जांचें और कृपया पुनः प्रयास करें।",
    "today": "आज",
    "followers": "समर्थक",
    "total": "कुल",
    "noticeBoard": "सूचना पट्ट",
    "viewAll": "सभी को देखें",
    'bhavChalitChart': 'भाव चलित चार्ट',
    'cusps': 'कुस्प्स',
    'planets': 'ग्रहों',
    'rulingPlanets': 'शासक ग्रह',
    "message": "संदेश",
    "senderCategory": "प्रेषक श्रेणी",
    "readMore": "और पढ़ें",
    'kp': 'केपी',
    'dasha': 'दशा',
    "showLess": "कम दिखाएं",
    "goLive": "रहने जाओ",
    "live": "लाइव",
    "congratulations": "बधाई हो",
    "tips": "सुझावों",
    "startLive": "लाइव प्रारंभ करें",
    "sessionType": "सत्र प्रकार",
    "chat": "बात करना",
    "totalMarksObtained": "कुल प्राप्त अंक",
    "call": "फोन",
    "offerType": "ऑफर का प्रकार",
    "firstFreeOffer": "पहला निःशुल्क परामर्श प्रस्ताव",
    "promotionOffer": "प्रमोशन ऑफर",
    "status": "दर्जा",
    "nextOnlineTiming": "अगली ऑनलाइन टाइमिंग",
    "follow": "अनुसरण करना",
    "astrologerId": "ज्योतिषी आईडी",
    "profileOptions": "प्रोफ़ाइल विकल्प",
    "profile": "प्रोफ़ाइल",
    "editProfile": "प्रोफ़ाइल संपादित करें",
    "orderHistory": "आदेश इतिहास",
    "bankDetails": "बैंक विवरण",
    "priceChangeRequest": "मूल्य परिवर्तन अनुरोध",
    "numberChangeRequest": "नंबर परिवर्तन अनुरोध",
    "primaryPhoneNumber": "प्राथमिक फोन नंबर",
    "secondaryPhoneNumber": "द्वितीय फ़ोन नंबर",
    "blockedUsers": "रोके गए उपयोगकर्ता",
    "reportComment": "रिपोर्ट टिप्पणी",
    "chatAssistance": "चैट सहायता",
    "chatAssistanceHome": "चैट सहायता",
    "suggestRemedy": "उपाय सुझाएं",
    "unblock": "अनब्लॉक",
    "performance": "प्रदर्शन",
    "rankSystem": "रैंक प्रणाली",
    "availabilityTitle": "आज की उपलब्धता (मिनटों में)",
    "searchBlockUserHint": "अवरोधित उपयोगकर्ता को खोजें",
    "ratings": "Ratings",
    "userReview": "रेटिंग",
    "years": "साल",
    "date": "तारीख",
    "overallScore": "समग्र प्राप्तांक",
    "update": "अद्यतन",
    "name": "नाम",
    "rank": "पद",
    "diamond": "डायमंड",
    "busyChat": "व्यस्त चैट",
    "busyCall": "व्यस्त कॉल",
    "availableChat": "उपलब्ध चैट",
    "availableLive": "लाइव उपलब्ध",
    "experience": "अनुभव",
    "availableCall": "उपलब्ध कॉल",
    "approved": "अनुमत",
    "serviceType": "सेवा प्रकार",
    "priceRequested": "मूल्य अनुरोधित",
    "requestRaised": "अनुरोध उठाया गया",
    "priceChangeBtn": "नई कीमत के लिए अनुरोध बढ़ाएं",
    "descriptions": "विवरण",
    "speciality": "स्पेशलिटी",
    "accountHolderName": "खाता धारक का नाम",
    "bankAccountNumber": "बैंक खाता संख्या",
    "attachments": "संलग्नक",
    "iFSCCode": "आईएफएससी कोड",
    "yourBankDetails": "आपका बैंक विवरण",
    "customerPrice": "ग्राहक मूल्य",
    "numChangeMsgTitle": "इन नंबरों पर आपको कॉल चैट अलर्ट मिलेंगे।",
    "requestPriceChangeBtn": "मूल्य परिवर्तन का अनुरोध करें",
    "hintTextName": "कृपया नाम दर्ज करें",
    "holderNameHintText": "कृपया धारक का नाम दर्ज करें",
    "accountNumHintText": "कृपया बैंक खाता संख्या दर्ज करें",
    "ifscCodeHintText": "कृपया बैंक आईएफएससी कोड दर्ज करें",
    "hintSpeciality": "कृपया विशेषता दर्ज करें",
    "hintDescriptions": "कृपया विवरण दर्ज करें",
    "hintExperience": "कृपया अनुभव दर्ज करें",
    "saveChanges": "परिवर्तनों को सुरक्षित करें",
    "availableBalance": "उपलब्ध \nशेष राशि",
    "pgCharges": "पीजी \nशुल्क",
    "subTotal": "उप\nकुल",
    "tds": "टीडीएस: ",
    "available": "उपलब्ध",
    "changeAppLanguage": "ऐप की भाषा बदलें",
    "astrologerRank": "ज्योतिषी रैंक",
    "busy": "व्यस्त",
    "deleteMyAccount": "मेरा एकाउंट हटा दो",
    "logoutMyAccount": "मेरा खाता लॉगआउट करें",
    "termsAndConditions": "नियम और शर्तें",
    "gst": "जीएसटी:",
    "uploadStory": "कहानी अपलोड करें",
    "customerSupport": "ग्राहक सहेयता",
    "chooseLanguage": "भाषा चुनें",
    "fAndQ": "एफ एंड क्यू",
    "priceChange": "मूल्य परिवर्तन",
    "numberChange": "संख्या परिवर्तन",
    "reportAnAstrologer": "किसी ज्योतिषी को रिपोर्ट करें",
    "uploadYourPhoto": "अपनी फोटो अपलोड करें",
    "general": "आम",
    "privacyPolicy": "गोपनीयता नीति",
    "english": "अंग्रेज़ी",
    "hindi": "हिन्दी",
    "marathi": "मराठी",
    "gujarati": "गुजराती",
    "totalAmount": "कुल \nराशि:",
    "referAnAstrologer": "किसी ज्योतिषी से संपर्क करें",
    "settings": "समायोजन",
    "contactUs": "संपर्क करें",
    "shareFeedback": "प्रतिक्रिया साझा करें",
    "importantNumbers": "महत्वपूर्ण संख्याएँ",
    "donation": "दान",
    "addContact": "संपर्क जोड़ें",
    "mobileNumber": "मोबाइल नंबर",
    "astrologySkill": "ज्योतिष कौशल",
    "platform": "प्लैटफ़ॉर्म",
    "mandatoryFields": "चिह्नित फ़ील्ड अनिवार्य हैं.",
    "submitForm": "फार्म जमा करें",
    "waitlist": "प्रतीक्षा सूची",
    "anotherPlatform":
        "क्या वे वर्तमान में किसी अन्य प्लेटफ़ॉर्म पर काम कर रहे हैं?",
    "enterNameMsg": "ज्योतिषी का नाम दर्ज करें",
    "enterNumberMsg": "ज्योतिषी का मोबाइल नंबर दर्ज करें",
    "enterSkillsMsg": "ज्योतिषी का कौशल दर्ज करें",
    "enterExperienceMsg": "ज्योतिषी का अनुभव दर्ज करें",
    "enterPlatformMsg":
        "जिस प्लेटफ़ॉर्म के लिए वे काम कर रहे हैं उसे दर्ज करें",
    "yourEarning": "आपकी कमाई",
    "lifeTimeEarning": "जीवन भर की कमाई",
    "totalEarning": "कुल कमाई",
    "chatEarning": "चैट से कमाई",
    "callEarning": "कॉल कमाई",
    "remediesLeft": "उपाय बचे",
    "waitingQueue": "प्रतीक्षा कतार",
    "nextInLine": "पंक्ति में अगला",
    "reportEarning": "कमाई की रिपोर्ट करें",
    "suggestedRemediesEarning": "कमाई के सुझाए उपाय",
    "help": "मदद ",
    "orderId": "आदेश कामतत्व  ",
    "gender": "लिंग ",
    "dob": "जन्म तिथि ",
    "pob": "पीओबी ",
    "orderDateTime": "आदेश दिनांक-समय ",
    "rate": "दर ",
    "duration": "अवधि : ",
    "priceChangeCondition": "मूल्य परिवर्तन अनुरोध के लिए शर्तें",
    "unBlockMsg":
        "यदि आप इस उपयोगकर्ता को अनब्लॉक करते हैं, तो वे फिर से आपके साथ प्लेटफ़ॉर्म पर जुड़ सकेंगे।",
    "refund": "धनवापसी",
    "liveGifts": "लाइव उपहार",
    "remedySuggested": "उपाय सुझाया",
    "wallet": "बटुआ",
    "all": "सभी",
    "suggest": "सुझाव देना",
    "suggestRemedies": "उपाय सुझाएं",
    "daily": "दैनिक",
    "weekly": "साप्ताहिक",
    "monthly": "महीने के",
    "custom": "कस्टम",
    "aboutPooja": "पूजा के बारे में",
    "suggestNow": "अभी सुझाव दें",
    "clientPaid": "ग्राहक भुगतान",
    "okay": "ठीक",
    "home": "घर",
    "eCommerce": "ई-कॉमर्स",
    "logout": "लॉग आउट",
    "scheduleNow": "अभी शेड्यूल करें",
    "trainingVideos": "प्रशिक्षण वीडियो",
    "VideoCall": "वीडियो कॉल",
    "deleteAccount": "खाता हटा दो",
    "deleteText": "क्या आप इस खाते को हटाने के लिए सुनिश्चित हैं ?",
    "logoutText": "क्या आप लॉग आउट करना चाहते हैं ?",
    "submitFeedback": "प्रतिपुष्टि दें",
    "feedbackHintText": "अपनी प्रतिक्रिया यहां टाइप करें!",
    "feedbacksText":
        "हमें बेहतर बनाने में मदद करने के लिए आप अपने विचार साझा करने के लिए स्वतंत्र हैं।",
    "anyFeedbacks": "कोई प्रतिपुष्टि?",
    "checkKundli": "कुंडली जांचें",
    "yes": "हाँ",
    "no": "नहीं",
    "checkYours": "अपना जांचें",
    "kundliText": "कुंडली",
    "male": "पुरुष",
    "female": "महिला",
    "birthTime": "जन्म समय",
    "submit": "जमा करना",
    "birthDetails": "जन्म विवरण",
    'personalDetails': 'व्यक्तिगत विवरण',
    "lagna": "लग्न",
    "moon": "चंद्रमा",
    "sun": "सूरज",
    "navamansha": "नवमांश",
    "dosha": "दोष",
    "gan": "गण",
    "sign": "संकेत",
    "yoni": "योनि",
    "nakshatra": "नक्षत्र",
    "varna": "वार्ना",
    "vashya": "वश्य",
    "nadi": "नाड़ी",
    "nakshatraLord": "नक्षत्र स्वामी",
    "signLord": "साइन भगवान",
    "liveHours": "लाइव घंटे",
    "busyHours": "व्यस्त घंटे",
    "charan": "चरण",
    "tatva": "तत्व",
    "day": "दिन",
    "conversionRate": "रूपांतरण दर",
    "onlineHours": "ऑनलाइन घंटे",
    "repurchaseRate": "पुनर्खरीद दर",
    "gold": "सोना",
    "unranked": "अन रैंक",
    "yog": "योग",
    "bronze": "पीतल",
    "silver": "चाँदी",
    "platinum": "प्लैटिनम",
    "sunset": "सूर्यास्त",
    "sunrise": "सूर्योदय",
    "karana": "करण",
    "noteText":
        "ध्यान दें: डेटा एक-एक बार की आवृत्ति के साथ नियमित ताज़ा चक्र से गुज़रेगा",
    "tithi": "तिथि",
    "prediction": "भविष्यवाणी",
    "birthPlace": "जन्म स्थान",
    "basicPanchang": "मूल पंचांग",
    "allFieldsText": "कृपया सभी फ़ील्ड भरें",
    "birthPalace": "जन्म महल",
    "confirmTimeBirth": "जन्म के समय की पुष्टि करें",
    "selectYourTimeBirth": "अपना जन्म समय चुनें",
    "birthDate": "जन्म तिथि",
    "confirmDateBirth": "जन्मतिथि की पुष्टि करें",
    "selectYourDateBirth": "अपनी जन्म तिथि चुनें",
    "checkOthers": "दूसरों की जाँच करें",
    "suggestRemediesHome": "उपाय \nसुझाएं",
    "chooseYourAppLanguage": "अपनी ऐप भाषा चुनें",
    "payAttention": "ध्यान देना",
    "yourScore": "तुम्हारे अंक",
    "previous": "पहले का",
    'deleteAccountMsg': 'क्या आप इस खाते को हटाने के लिए सुनिश्चित हैं ?',
    "next": "अगला",
    "close": "बंद करना",
    "viewScore": "स्कोर देखें",
    "gotIt": "समझ गया",
    'itSpam': 'यह एक स्पैम है',
    'hateSpeechSymbols': 'नफरत फैलाने वाले भाषण या प्रतीक',
    'violenceOrganisations': 'हिंसा या खतरनाक संगठन',
    'falseInformation': 'झूठी सूचना',
    'scamFraud': 'घोटाला धोखाधड़ी',
    'bullyingHarassment': 'बदमाशी उत्पीड़न',
    'thankYouForReporting': 'रिपोर्टिंग के लिए धन्यवाद!',
    'thankYouDes':
        'हम आपकी रिपोर्ट की समीक्षा करेंगे और आवश्यक कार्रवाई की जाएगी.',
    'bankName': 'बैंक का नाम',
    'vimshottari': 'विमशोत्तरी',
    'yogini': 'योगिनी',
    'mahadasha': 'महादशा',
    'antarDasha': 'अंतर दशा',
    'pratyantarDasha': 'प्रत्यंतर दशा',
    'sookshmaDasha': 'सूक्ष्म दशा',
    'pranDasha': 'प्राण दशा',
    'noDataAntarDasha': 'अंतरदशा के अंदर कोई डेटा नहीं मिला',
    'noDataPratyantarDasha': 'प्रत्यंतर दशा के अंदर कोई डेटा नहीं मिला',
    'noDataSookshmaDasha': 'सूक्ष्म दशा के अंदर कोई डेटा नहीं मिला',
    'noDataPranDasha': 'प्राण दशा के अंदर कोई डेटा नहीं मिला',
    'mahadashNote': 'ऊपर बताई गई तारीखें अंतिम तारीखें हैं।',
    'bhadrika': 'भद्रिका',
    'rashiChart': 'राशि चार्ट',
    'levelUp': 'ऊपर का स्तर',
    'physical': 'भौतिक',
    'character': 'चरित्र',
    'health': 'स्वास्थ्य',
    'education': 'शिक्षा',
    'family': 'परिवार',
    "jobTitle": "अच्छा काम! कोई भी प्रतीक्षा सूची में नहीं है.",
    "contactPermissionRequired": "संपर्क अनुमति आवश्यक है",
    "contactSaved": "संपर्क सफलतापूर्वक सहेजा गया",
    "Saved": "बचाया",
    'otpVerification': 'ओटीपी सत्यापन',
    'otpTextMsg': 'हमारे द्वारा भेजे गए एसएमएस से कोड दर्ज करें',
    'notReceiveOTP': "ओटीपी नहीं मिला?",
    'resend': 'पुन: भेजें',
    'noAttemptsLeft': 'कोई प्रयास नहीं बचा!',
    'attemptsRemaining': 'प्रयास बाकी है',
    'phoneNumberMustBe10Digit': 'फ़ोन नंबर 10 अंकों का होना चाहिए',
    'specialityNotEmpty': "विशेषता खाली नहीं हो सकती",
    "customerCare": "ग्राहक देखभाल",
    'ScheduleOnlineDate': 'अपनी अगली ऑनलाइन तिथि निर्धारित करें',
    'confirmNextDate': 'अगली ऑनलाइन तिथि की पुष्टि करें',
    'scheduleOnlineTime': 'अपना अगला ऑनलाइन समय निर्धारित करें',
    'confirmOnlineTime': 'अगले ऑनलाइन समय की पुष्टि करें',
    'actualPayment': 'वास्तविक भुगतान',
    "amount": "मात्रा",
    "lastBillingCycle": "अंतिम बिलिंग चक्र",
    "totalTax": "कुल कर",
    "paymentGateway": "भुगतान गेटवे",
    "toBeSettled": "व्यवस्थित होना",
    "timePeriod": "समय सीमा",
    "selectCustomDate": "कस्टम तिथि चुनें",
    "selectStartDate": "आरंभ तिथि चुनें",
    "startDate": "आरंभ करने की तिथि",
    "selectEndDate": "अंतिम तिथि चुनें",
    "confirm": "पुष्टि करना",
    "endDate": "अंतिम तिथि",
    "title": "शीर्षक",
    "percentage": "प्रतिशत",
    "marks": "गुण",
    "last30DaysAvailability": "पिछले 30 दिनों की उपलब्धता",
    "inMins": "मिनटों में",
    "select": "चुनना",
    "replyHere": "यहां उत्तर दें",
    "selectCountry": "कोई देश चुनें",
    "searchCountry": "एक देश खोजें",
    "verificationHintText": "सत्यापन के लिए आपको ऊपर दिए गए नंबर पर कॉल आएगी",
    "verify": "सत्यापित करें",
    "validPhoneNumber": "कृपया एक वैध नंबर डालें",
    "mobileNumber10Digits": "मोबाइल नंबर 10 अंकों का होना चाहिए",
    "enterRegisteredNumber": "पंजीकृत संख्या दर्ज करें",
    "passBook": "पासवृक",
    "cancelledCheque": "रद्द किया गया चेक",
    "noResultFound": "कोई परिणाम नहीं मिला",
    "astrologer": "ज्योतिषी",
    "thankYouHelp": "आपकी मदद के लिए आपको धन्यवाद",
    "chatEnded": "यह चैट ख़त्म हो चुकी है",
    "unreadMessages": "अपठित संदेश",
    "addSpeciality": "विशेषता जोड़ें",
    "pleaseEnterYourName": "कृपया अपना नाम दर्ज करें",
    "selectBirthDate": "जन्मतिथि चुनें",
    "selectBirthTime": "जन्म समय चुनें",
    "selectBirthPlace": "जन्म स्थान चुनें",
    "nameEmptyValidation": "नाम खाली नहीं होना चाहिए",
    "dateEmptyValidation": "दिनांक रिक्त नहीं होना चाहिए",
    "timeEmptyValidation": "समय खाली नहीं होना चाहिए",
    "PlaceEmptyValidation": "जगह खाली नहीं होनी चाहिए",
    'manglikDosha': 'मांगलिक दोष',
    'kalsarpDosha': 'कालसर्प दोष',
    'sadesathiDosha': 'साढ़ेसाती दोष',
    'pitriDosha': 'पितृ दोष',
    'degree': 'डिग्री',
    "astrologersLiveStar": "ज्योतिषियों का लाइव स्टार",
    'sayHi': 'नमस्ते कहे',
    "dateTime": "दिनांक समय",
    "giftName": "उपहार का नाम",
    "giftPrice": "उपहार मूल्य",
    "quantity": "मात्रा",
    "selectVideo": "वीडियो चुनें",
    "donateNow": "अभी दान कीजिए",
    "enterCustomAmount": "कस्टम राशि दर्ज करें",
    "enterAmount": "राशि डालें",
    "importNumText": "आपको इन नंबरों से कॉल और चैट अलर्ट मिलेंगे। किसी भी भ्रम से बचने के लिए इन नंबरों को सेव करें।",
    "somethingWentWrong": "कुछ गलत हो गया",
    "version": "संस्करण",
    "feedbackValidation": "कृपया अपनी प्रतिक्रिया दर्ज करें",
    "reportingQue": "आप इसकी सूचना क्यों दे रहे हैं",

  };
}