Map<String, String> mr() {
  return {
    "noInternetConnection": "कृपया तुमचे इंटरनेट कनेक्शन तपासा",
    "timeoutMessage":
        "काहीतरी चूक झाली.\nकृपया तुमचे इंटरनेट कनेक्शन तपासा आणि पुन्हा प्रयत्न करा.",
    "today": "आज",
    "followers": "अनुयायी",
    "total": "एकूण @count",
    "noticeBoard": "सूचना फलक",
    "viewAll": "सर्व पहा",
    "message": "संदेश",
    'kp': 'केपी',
    'dasha': 'दशा',
    "senderCategory": "प्रेषक श्रेणी",
    'bhavChalitChart': 'भाव चालित चार्ट',
    'cusps': 'कुस्प्स',
    'cusp': 'कस्प',
    'noDataToShow': 'दर्शविण्यासाठी कोणताही डेटा नाही',
    'planets': 'ग्रह',
    'rulingPlanets': 'सत्ताधारी ग्रह',
    'vimshottari': 'विमशोत्तरी',
    "readMore": "पुढे वाचा",
    "showLess": "कमी दाखवा",
    "goLive": "थेट जा",
    "priceChange": "किंमत बदल",
    "reportAnAstrologer": "ज्योतिषाला कळवा",
    "numberChange": "संख्या बदल",
    "live": "राहतात",
    "uploadStory": "कथा अपलोड करा",
    "uploadYourPhoto": "तुमचा फोटो अपलोड करा",
    "customerSupport": "ज्योतिष सहाय्यता",
    "chooseLanguage": "भाषा निवडा",
    "fAndQ": "f&Q",
    "congratulations": "अभिनंदन",
    "tips": "टिपा",
    "startLive": "लाइव्ह सुरू करा",
    "sessionType": "सत्राचा प्रकार",
    "chat": "गप्पा",
    "totalMarksObtained": "एकूण गुण मिळाले",
    "call": "कॉल करा",
    "offerType": "ऑफर प्रकार",
    "firstFreeOffer": "पहिली मोफत सल्लामसलत ऑफर",
    "promotionOffer": "प्रमोशन ऑफर",
    "status": "स्थिती",
    "nextOnlineTiming": "पुढील ऑनलाइन वेळ",
    "follow": "अनुसरण करा",
    "astrologerId": "ज्योतिषी आयडी",
    "profileOptions": "प्रोफाइल पर्याय",
    "profile": "प्रोफाइल",
    "editProfile": "प्रोफाईल संपादित करा",
    "orderHistory": "ऑर्डर इतिहास",
    "bankDetails": "बँक तपशील",
    "priceChangeRequest": "किंमत बदलाची विनंती",
    "numberChangeRequest": "क्रमांक बदलण्याची विनंती",
    "primaryPhoneNumber": "प्राथमिक फोन नंबर",
    "secondaryPhoneNumber": "दुय्यम फोन नंबर",
    "blockedUsers": "अवरोधित वापरकर्ते",
    "reportComment": "टिप्पणी नोंदवा",
    "chatAssistance": "गप्पा सहाय्य",
    "chatAssistanceHome": "गप्पा सहाय्य",
    "suggestRemedy": "उपाय सुचवा",
    "unblock": "अनब्लॉक करा",
    "performance": "कामगिरी",
    "rankSystem": "रँक सिस्टम",
    "availabilityTitle": "आजची उपलब्धता (मिनिटांमध्ये)",
    "searchBlockUserHint": "अवरोधित वापरकर्त्यासाठी शोधा",
    "ratings": "रेटिंग",
    "userReview": "वापरकर्ता पुनरावलोकन",
    "years": "वर्षे",
    "date": "तारीख",
    "overallScore": "एकूण स्कोअर",
    "update": "अपडेट करा",
    "name": "नाव",
    "rank": "रँक",
    "diamond": "हिरा",
    "busyChat": "व्यस्त गप्पा",
    "busyCall": "व्यस्त कॉल",
    "availableChat": "उपलब्ध गप्पा",
    "availableLive": "थेट उपलब्ध",
    "experience": "अनुभव",
    "availableCall": "उपलब्ध कॉल",
    "approved": "मंजूर",
    "serviceType": "सेवा प्रकार",
    "priceRequested": "किंमत मागितली",
    "requestRaised": "विनंती उठवली",
    "priceChangeBtn": "नवीन किंमतीसाठी विनंती वाढवा",
    "descriptions": "वर्णने",
    "speciality": "खासियत",
    "accountHolderName": "खातेधारकाचे नाव",
    "bankAccountNumber": "बँक खाते क्रमांक",
    "attachments": "संलग्नक",
    "iFSCCode": "IFSC कोड",
    "yourBankDetails": "तुमचे बँक तपशील",
    "customerPrice": "ग्राहक किंमत",
    "numChangeMsgTitle": "या नंबरवर तुम्हाला कॉल चॅट अलर्ट मिळतील.",
    "requestPriceChangeBtn": "किंमत बदलण्याची विनंती करा",
    "hintTextName": "कृपया नाव प्रविष्ट करा",
    "holderNameHintText": "कृपया धारकाचे नाव प्रविष्ट करा",
    "accountNumHintText": "कृपया बँक खाते क्रमांक प्रविष्ट करा",
    "ifscCodeHintText": "कृपया बँकेचा IFSC कोड प्रविष्ट करा",
    "hintSpeciality": "कृपया स्पेशॅलिटी एंटर करा",
    "hintDescriptions": "कृपया वर्णन प्रविष्ट करा",
    "hintExperience": "कृपया अनुभव प्रविष्ट करा",
    "saveChanges": "बदल जतन करा",
    "availableBalance": "उपलब्ध \nशिल्लक",
    "pgCharges": "PG \nशुल्क",
    "subTotal": "उप\nएकूण",
    "tds": "TDS: ",
    "available": "उपलब्ध",
    "changeAppLanguage": "अॅपची भाषा बदला",
    "astrologerRank": "ज्योतिषी रँक",
    "busy": "व्यस्त",
    "deleteMyAccount": "माझे खाते हटवा",
    "logoutMyAccount": "माझे खाते लॉगआउट करा",
    "termsAndConditions": "नियम आणि अटी",
    "gst": "जीएसटी:",
    "general": "सामान्य",
    "privacyPolicy": "गोपनीयता धोरण",
    "english": "इंग्रजी",
    "hindi": "हिंदी",
    "marathi": "मराठी",
    "gujarati": "गुजराती",
    "totalAmount": "एकूण \nरक्कम:",
    "referAnAstrologer": "ज्योतिषाचा संदर्भ घ्या",
    "settings": "सेटिंग्ज",
    "contactUs": "आमच्याशी संपर्क साधा",
    "shareFeedback": "अभिप्राय शेअर करा",
    "importantNumbers": "महत्वाची संख्या",
    "donation": "दान",
    "addContact": "संपर्क जोडा",
    "mobileNumber": "मोबाईल नंबर",
    "astrologySkill": "ज्योतिष कौशल्य",
    "platform": "प्लॅटफॉर्म",
    "mandatoryFields": "चिन्हांकित फील्ड अनिवार्य आहेत.",
    "submitForm": "आवेदन सादर करा",
    "waitlist": "प्रतीक्षा यादी",
    "anotherPlatform": "ते सध्या इतर कोणत्याही प्लॅटफॉर्मवर काम करत आहेत का?",
    "enterNameMsg": "ज्योतिषाचे नाव प्रविष्ट करा",
    "enterNumberMsg": "ज्योतिषाचा मोबाईल नंबर टाका",
    "enterSkillsMsg": "ज्योतिषी कौशल्य प्रविष्ट करा",
    "enterExperienceMsg": "ज्योतिषाचा अनुभव प्रविष्ट करा",
    "enterPlatformMsg": "ते ज्या प्लॅटफॉर्मसाठी काम करत आहेत त्यात प्रवेश करा",
    "yourEarning": "तुमची कमाई",
    "lifeTimeEarning": "लाइफ टाइम कमाई",
    "totalEarning": "एकूण कमाई",
    "chatEarning": "चॅट कमाई",
    "callEarning": "कॉल कमाई",
    "remediesLeft": "उपाय बाकी",
    "waitingQueue": "प्रतीक्षा रांग",
    "nextInLine": "पुढील ओळीत",
    "reportEarning": "कमाईचा अहवाल द्या",
    "suggestedRemediesEarning": "सुचवलेले उपाय कमाई",
    "help": "मदत करा ",
    "orderId": "ऑर्डर आयडी   ",
    "gender": "लिंग  ",
    "dob": "डीओबी  ",
    "pob": "पीओबी  ",
    "orderDateTime": "ऑर्डरची तारीख-वेळ ",
    "rate": "दर  ",
    "duration": "कालावधी ",
    "priceChangeCondition": "किंमत बदल विनंतीसाठी अटी",
    "unBlockMsg":
        "तुम्ही या वापरकर्त्याला अनब्लॉक केल्यास, ते पुन्हा तुमच्याशी प्लॅटफॉर्मवर कनेक्ट होऊ शकतील.",
    "refund": "परतावा",
    "liveGifts": "थेट भेटवस्तू",
    "remedySuggested": "उपाय सुचवला",
    "wallet": "पाकीट",
    "all": "सर्व",
    "suggest": "सूचित",
    "suggestRemedies": "उपाय सुचवा",
    "daily": "दररोज",
    "weekly": "साप्ताहिक",
    "monthly": "मासिक",
    "custom": "सानुकूल",
    "aboutPooja": "पूजा बद्दल",
    "suggestNow": "आता सुचवा",
    "clientPaid": "ग्राहकाने पैसे दिले",
    "okay": "ठीक आहे",
    "home": "मुख्यपृष्ठ",
    "eCommerce": "ई-कॉमर्स",
    "scheduleNow": "आता शेड्यूल करा",
    "trainingVideos": "प्रशिक्षण व्हिडिओ",
    "VideoCall": "व्हिडिओ कॉल",
    "logout": "बाहेर पडणे",
    "deleteAccount": "खाते हटवा",
    "deleteText": "तुमची खात्री आहे की तुम्ही तुमचे खाते हटवू इच्छिता?",
    "logoutText": "तुमची खात्री आहे की तुम्ही लॉगआउट करू इच्छिता?",
    "submitFeedback": "अभिप्राय सबमिट करा",
    "anyFeedbacks": "कोणताही अभिप्राय?",
    "feedbackHintText": "तुमचा अभिप्राय येथे टाइप करा!",
    "feedbacksText":
        "आम्हाला सुधारण्यात मदत करण्यासाठी तुम्ही तुमचे विचार शेअर करण्यास मोकळे आहात.",
    "checkKundli": "कुंडली तपासा",
    "yes": "होय",
    "no": "नाही",
    "checkYours": "तुमचे तपासा",
    "checkOthers": "इतर तपासा",
    "kundliText": "कुंडली",
    "male": "पुरुष",
    "female": "स्त्री",
    "birthTime": "जन्मवेळ",
    "birthPalace": "जन्म महाल",
    "submit": "प्रस्तुत करणे",
    'personalDetails': 'वैयक्तिक माहिती',
    "lagna": "लग्न",
    "moon": "चंद्र",
    "sun": "रवि",
    "gan": "गण",
    "liveHours": "थेट तास",
    "busyHours": "व्यस्त तास",
    "signLord": "स्वाक्षरी स्वामी",
    "SignLord": "स्वाक्षरी\nस्वामी",
    "starLord": "नक्षत्र\nस्वामी",
    "subLord": "उप\nस्वामी",
    "sign": "संकेत",
    "yoni": "योनी",
    "varna": "वर्ण",
    "vashya": "वश्या",
    "nadi": "नाडी",
    "onlineHours": "ऑनलाइन तास",
    "repurchaseRate": "पुनर्खरेदी दर",
    "bronze": "कांस्य",
    "conversionRate": "रूपांतरण दर",
    "unranked": "अन रँक",
    "tithi": "तिथी",
    "yog": "योग",
    "silver": "चांदी",
    "sunrise": "सूर्योदय",
    "gold": "सोने",
    "platinum": "प्लॅटिनम",
    "noteText":
        "टीप: डेटा नियमित रिफ्रेश चक्रातून जाईल ज्याची वारंवारता प्रत्येक वेळी एकदाच असेल",
    "day": "दिवस",
    "karana": "करण",
    "sunset": "सूर्यास्त",
    "charan": "चरण",
    "tatva": "तत्व",
    "nakshatra": "नक्षत्र",
    "nakshatraLord": "नक्षत्र भगवान",
    "dosha": "दोष",
    "birthPlace": "जन्मस्थान",
    "prediction": "अंदाज",
    "basicPanchang": "मूळ पंचांग",
    "navamansha": "नवमांश",
    "birthDetails": "जन्म तपशील",
    "allFieldsText": "कृपया सर्व फील्ड भरा",
    "confirmTimeBirth": "जन्माच्या वेळेची पुष्टी करा",
    "selectYourTimeBirth": "तुमची जन्म वेळ निवडा",
    "birthDate": "जन्मदिनांक",
    "confirmDateBirth": "जन्मतारीख निश्चित करा",
    "selectYourDateBirth": "तुमची जन्मतारीख निवडा",
    "suggestRemediesHome": "उपाय \nसुचवा",
    "chooseYourAppLanguage": "तुमची अॅप भाषा निवडा",
    "payAttention": "लक्ष द्या",
    "yourScore": "तुमचा स्कोअर",
    "previous": "मागील",
    "next": "पुढे",
    "close": "बंद",
    "viewScore": "स्कोअर पहा",
    'deleteAccountMsg': 'तुमची खात्री आहे की तुम्ही तुमचे खाते हटवू इच्छिता?',
    "gotIt": "समजले",
    'itSpam': 'तो एक स्पॅम आहे',
    'hateSpeechSymbols': 'द्वेषयुक्त भाषण किंवा चिन्हे',
    'violenceOrganisations': 'हिंसा किंवा धोकादायक संघटना',
    'falseInformation': 'खोटी माहिती',
    'scamFraud': 'घोटाळा फसवणूक',
    'bullyingHarassment': 'गुंडगिरीचा छळ',
    'thankYouForReporting': 'अहवाल दिल्याबद्दल धन्यवाद!',
    'thankYouDes':
        'आम्ही तुमच्या अहवालाचे पुनरावलोकन करू आणि आवश्यक ती कारवाई केली जाईल.',
    'bankName': 'बँकेचे नाव',
    'yogini': 'योगिनी',
    'mahadasha': 'महादशा',
    'antarDasha': 'अंतरदशा',
    'pratyantarDasha': 'प्रत्यंतर दशा',
    'sookshmaDasha': 'सूक्ष्म दशा',
    'pranDasha': 'प्राण दशा',
    'noDataAntarDasha': 'अंतरदशा के अंदर कोई डेटा नहीं मिला',
    'noDataPratyantarDasha': 'प्रत्यंतर दशा के अंदर कोई डेटा नहीं मिला',
    'noDataSookshmaDasha': 'सूक्ष्म दशा के अंदर कोई डेटा नहीं मिला',
    'noDataPranDasha': 'प्राण दशा के अंदर कोई डेटा नहीं मिला',
    'mahadashNote': 'वर नमूद केलेल्या तारखा शेवटच्या तारखा आहेत.',
    'bhadrika': 'भद्रिका',
    'rashiChart': 'राशी चार्ट',
    'levelUp': 'पातळी वर',
    'physical': 'शारीरिक',
    'character': 'वर्ण',
    'health': 'आरोग्य',
    'education': 'शिक्षण',
    'family': 'कुटुंब',
    "jobTitle": "चांगले काम! प्रतीक्षा यादीत कोणीही नाही.",
    "contactSaved": "संपर्क यशस्वीरित्या जतन केला",
    "contactPermissionRequired": "संपर्क परवानगी आवश्यक आहे",
    "Saved": "जतन",
    'otpVerification': 'OTP पडताळणी',
    'otpTextMsg': 'आम्ही पाठवलेल्या एसएमएसमधील कोड प्रविष्ट करा',
    'notReceiveOTP': "OTP प्राप्त झाला नाही?",
    'resend': 'पुन्हा पाठवा',
    'noAttemptsLeft': 'प्रयत्न सोडले नाहीत!',
    'attemptsRemaining': 'प्रयत्न बाकी',
    'phoneNumberMustBe10Digit': 'फोन नंबर 10 अंकी असणे आवश्यक आहे',
    'specialityNotEmpty': "स्पेशॅलिटी रिक्त असू शकत नाही",
    "customerCare": "ज्योतिष सेवा",
    'ScheduleOnlineDate': 'तुमची पुढील ऑनलाइन तारीख शेड्यूल करा',
    'confirmNextDate': 'पुढील ऑनलाइन तारखेची पुष्टी करा',
    'scheduleOnlineTime': 'तुमची पुढील ऑनलाइन वेळ शेड्यूल करा',
    'confirmOnlineTime': 'पुढील ऑनलाइन वेळेची पुष्टी करा',
    'actualPayment': 'वास्तविक पेमेंट',
    "amount": "रक्कम",
    "lastBillingCycle": "अंतिम बिलिंग सायकल",
    "totalTax": "एकूण कर",
    "paymentGateway": "प्रदानाची द्वारमार्गिका",
    "toBeSettled": "सेटल करणे",
    "timePeriod": "कालावधी",
    "selectCustomDate": "सानुकूल तारीख निवडा",
    "selectStartDate": "प्रारंभ तारीख निवडा",
    "startDate": "प्रारंभ तारीख",
    "selectEndDate": "समाप्ती तारीख निवडा",
    "confirm": "पुष्टी",
    "endDate": "शेवटची तारीख",
    "title": "शीर्षक",
    "percentage": "टक्केवारी",
    "marks": "गुण",
    "last30DaysAvailability": "शेवटच्या 30 दिवसांची उपलब्धता",
    "inMins": "मिनिटांत",
    "select": "निवडा",
    "replyHere": "येथे उत्तर द्या",
    "selectCountry": "एक देश निवडा",
    "searchCountry": "देश शोधा",
    "verificationHintText": "पडताळणीसाठी तुम्हाला वर दिलेल्या नंबरवर कॉल येईल",
    "verify": "सत्यापित करा",
    "validPhoneNumber": "कृपया वैध फोन नंबर प्रविष्ट करा.",
    "mobileNumber10Digits": "मोबाईल नंबर 10 अंकी असावा.",
    "enterRegisteredNumber": "नोंदणीकृत क्रमांक प्रविष्ट करा",
    "passBook": "पासबुक",
    "cancelledCheque": "चेक रद्द केला",
    "noResultFound": "कोणताही परिणाम आढळला नाही",
    "astrologer": "ज्योतिषी",
    "thankYouHelp": "तुमच्या मदतीबद्दल धन्यवाद",
    "chatEnded": "ही गप्पा संपली",
    "unreadMessages": "न वाचलेले संदेश",
    "addSpeciality": "स्पेशॅलिटी जोडा",
    "pleaseEnterYourName": "कृपया आपले नाव प्रविष्ट करा",
    "selectBirthDate": "जन्मतारीख निवडा",
    "selectBirthTime": "जन्म वेळ निवडा",
    "selectBirthPlace": "जन्मस्थान निवडा",
    "nameEmptyValidation": "नाव रिकामे नसावे",
    "dateEmptyValidation": "तारीख रिकामी नसावी",
    "timeEmptyValidation": "वेळ रिकामा नसावा",
    "PlaceEmptyValidation": "जागा रिकामी नसावी",
    'manglikDosha': 'मांगलिक दोष',
    'kalsarpDosha': 'कालसर्प दोष',
    'sadesathiDosha': 'सदेसठी दोषा',
    'pitriDosha': 'पितृ दोष',
    'degree': 'पदवी',
    "astrologersLiveStar": "ज्योतिषांचा थेट तारा",
    'sayHi': 'हाय म्हणा',
    "dateTime": "तारीख वेळ",
    "giftName": "भेट नाव",
    "giftPrice": "भेट किंमत",
    "quantity": "प्रमाण",
    "selectVideo": "व्हिडिओ निवडा",
    "donateNow": "आता दान करा",
    "enterCustomAmount": "सानुकूल रक्कम प्रविष्ट करा",
    "enterAmount": "रक्कम प्रविष्ट करा",
    "importNumText":
        "तुम्हाला या नंबरवरून कॉल आणि चॅट अलर्ट मिळतील. कोणताही गोंधळ टाळण्यासाठी हे नंबर सेव्ह करा.",
    "somethingWentWrong": "काहीतरी चूक झाली",
    "version": "आवृत्ती",
    "feedbackValidation": "कृपया तुमचा अभिप्राय प्रविष्ट करा",
    "reportingQue": "तुम्ही याची तक्रार का करत आहात",
    "mobileNumberEmptyMsg": "कृपया मोबाईल नंबर टाका.",
    "uploadYourPhotos": "तुमचे फोटो अपलोड करा",
    "uploadImages": "प्रतिमा अपलोड करा",
    "imageValidationMsg": "प्रतिमा 5 पेक्षा जास्त असू शकत नाही",
    "profileUpdatedSuccessfully": "प्रोफाइल यशस्वीरित्या अपडेट केले",
    'pleaseWait': 'कृपया थांबा...',
    'fromCalls': 'कॉल्सवरून',
    'fromVideoCalls': 'व्हिडिओ कॉल्सवरून',
    'fromPrivateCalls': 'खाजगी कॉल्सवरून',
    'fromLiveGifts': 'थेट भेटवस्तू पासून',
    "YouHaveEarnedFromYourLastSession":
        "तुम्ही तुमच्या शेवटच्या सत्रातून ₹@price कमावले आहेत",
    "YouHaveReceivedCalls": "तुम्हाला @count कॉल प्राप्त झाले आहेत.",
    "YouHaveReceivedVideoCalls":
        "तुम्हाला @count व्हिडिओ कॉल प्राप्त झाले आहेत.",
    "YouHaveReceivedPrivateCalls":
        "तुम्हाला @count खाजगी कॉल प्राप्त झाले आहेत.",
    "YouHaveReceivedLiveGifts": "तुम्हाला @count थेट भेटवस्तू मिळाल्या आहेत.",
    "isOnCall": "कॉलवर आहे",
    'orderDetails':'ऑर्डर तपशील',
    'orderType':'ऑर्डर प्रकार',
    'walletBalance':'वॉलेट बॅलन्स',
    'maximumOrderTime':'जास्तीत जास्त ऑर्डर वेळ',
    'specialty':'स्पेशालिटी',
    'languageProficiency':'भाषा प्रवीणता',
    'astrologerRating':'ज्योतिषी रेटिंग',
    'addkundali': 'कुंडली घाला',
    'addKundaliText': 'मोफत वैयक्तिकृत कुंडली मिळविण्यासाठी खालील तपशील भरा',
  };
}
