Map<String, String> mr() {
  return {
    "noInternetConnection": "कृपया तुमचे इंटरनेट कनेक्शन तपासा",
    "timeoutMessage":
        "काहीतरी चूक झाली.\nकृपया तुमचे इंटरनेट कनेक्शन तपासा आणि पुन्हा प्रयत्न करा.",
    "today": "आज",
    "followers": "अनुयायी",
    "total": "एकूण",
    "noticeBoard": "सूचना फलक",
    "viewAll": "सर्व पहा",
    "message": "संदेश",
    "senderCategory": "प्रेषक श्रेणी",
    "readMore": "पुढे वाचा",
    "showLess": "कमी दाखवा",
    "goLive": "थेट जा",
    "live": "राहतात",
    "congratulations": "अभिनंदन",
    "tips": "टिपा",
    "startLive": "लाइव्ह सुरू करा",
    "sessionType": "सत्राचा प्रकार",
    "chat": "गप्पा",
    "totalMarksObtained": "एकूण गुण मिळाले",
    "call": "कॉल करा",
    "offerType": "ऑफर प्रकार",
    "firstFreeOffer": "पहिली मोफत सल्लामसलत ऑफर",
    "promotionOffer": "प्रमोशन ऑफर",
    "status": "स्थिती",
    "nextOnlineTiming": "पुढील ऑनलाइन वेळ",
    "follow": "अनुसरण करा",
    "customerId": "ग्राहक आयडी",
    "profileOptions": "प्रोफाइल पर्याय",
    "profile": "प्रोफाइल",
    "editProfile": "प्रोफाईल संपादित करा",
    "orderHistory": "ऑर्डर इतिहास",
    "bankDetails": "बँक तपशील",
    "priceChangeRequest": "किंमत बदलाची विनंती",
    "numberChangeRequest": "क्रमांक बदलण्याची विनंती",
    "primaryPhoneNumber": "प्राथमिक फोन नंबर",
    "secondaryPhoneNumber": "दुय्यम फोन नंबर",
    "blockedUsers": "अवरोधित वापरकर्ते",
    "reportComment": "टिप्पणी नोंदवा",
    "chatAssistance": "गप्पा सहाय्य",
    "suggestRemedy": "उपाय सुचवा",
    "unblock": "अनब्लॉक करा",
    "performance": "कामगिरी",
    "rankSystem": "रँक सिस्टम",
    "availabilityTitle": "आजची उपलब्धता (मिनिटांमध्ये)",
    "searchBlockUserHint": "अवरोधित वापरकर्त्यासाठी शोधा",
    "ratings": "रेटिंग",
    "userReview": "वापरकर्ता पुनरावलोकन",
    "years": "वर्षे",
    "date": "तारीख",
    "overallScore": "एकूण स्कोअर",
    "update": "अपडेट करा",
    "name": "नाव",
    "rank": "रँक",
    "diamond": "हिरा",
    "busyChat": "व्यस्त गप्पा",
    "busyCall": "व्यस्त कॉल",
    "availableChat": "उपलब्ध गप्पा",
    "availableLive": "थेट उपलब्ध",
    "experience": "अनुभव",
    "availableCall": "उपलब्ध कॉल",
    "approved": "मंजूर",
    "serviceType": "सेवा प्रकार",
    "priceRequested": "किंमत मागितली",
    "requestRaised": "विनंती उठवली",
    "priceChangeBtn": "नवीन किंमतीसाठी विनंती वाढवा",
    "descriptions": "वर्णने",
    "speciality": "खासियत",
    "accountHolderName": "खातेधारकाचे नाव",
    "bankAccountNumber": "बँक खाते क्रमांक",
    "attachments": "संलग्नक",
    "iFSCCode": "IFSC कोड",
    "yourBankDetails": "तुमचे बँक तपशील",
    "customerPrice": "ग्राहक किंमत",
    "numChangeMsgTitle": "या नंबरवर तुम्हाला कॉल चॅट अलर्ट मिळतील.",
    "requestPriceChangeBtn": "किंमत बदलण्याची विनंती करा",
    "hintTextName": "कृपया नाव प्रविष्ट करा",
    "holderNameHintText": "कृपया धारकाचे नाव प्रविष्ट करा",
    "accountNumHintText": "कृपया बँक खाते क्रमांक प्रविष्ट करा",
    "ifscCodeHintText": "कृपया बँकेचा IFSC कोड प्रविष्ट करा",
    "hintSpeciality": "कृपया स्पेशॅलिटी एंटर करा",
    "hintDescriptions": "कृपया वर्णन प्रविष्ट करा",
    "hintExperience": "कृपया अनुभव प्रविष्ट करा",
    "saveChanges": "बदल जतन करा",
    "availableBalance": "उपलब्ध \nशिल्लक:",
    "pgCharges": "PG \nशुल्क:",
    "subTotal": "उप\nएकूण:",
    "tds": "TDS: ",
    "available": "उपलब्ध",
    "changeAppLanguage": "अॅपची भाषा बदला",
    "astrologerRank": "ज्योतिषी रँक",
    "busy": "व्यस्त",
    "deleteMyAccount": "माझे खाते हटवा",
    "logoutMyAccount": "माझे खाते लॉगआउट करा",
    "termsAndConditions": "नियम आणि अटी",
    "gst": "जीएसटी:",
    "general": "सामान्य",
    "privacyPolicy": "गोपनीयता धोरण",
    "english": "इंग्रजी",
    "totalAmount": "एकूण \nरक्कम:",
    "referAnAstrologer": "ज्योतिषाचा संदर्भ घ्या:",
    "settings": "सेटिंग्ज",
    "contactUs": "आमच्याशी संपर्क साधा:",
    "shareFeedback": "अभिप्राय शेअर करा:",
    "importantNumbers": "महत्वाची संख्या",
    "donation": "दान:",
    "addContact": "संपर्क जोडा",
    "mobileNumber": "मोबाईल नंबर*",
    "astrologySkill": "ज्योतिष कौशल्य*",
    "platform": "प्लॅटफॉर्म",
    "mandatoryFields": "*चिन्हांकित फील्ड अनिवार्य आहेत.*",
    "submitForm": "आवेदन सादर करा",
    "waitlist": "प्रतीक्षा यादी",
    "anotherPlatform": "ते सध्या इतर कोणत्याही प्लॅटफॉर्मवर काम करत आहेत का?",
    "enterNameMsg": "ज्योतिषाचे नाव प्रविष्ट करा",
    "enterNumberMsg": "ज्योतिषाचा मोबाईल नंबर टाका",
    "enterSkillsMsg": "ज्योतिषी कौशल्य प्रविष्ट करा",
    "enterExperienceMsg": "ज्योतिषाचा अनुभव प्रविष्ट करा",
    "enterPlatformMsg": "ते ज्या प्लॅटफॉर्मसाठी काम करत आहेत त्यात प्रवेश करा",
    "yourEarning": "तुमची कमाई",
    "lifeTimeEarning": "लाइफ टाइम कमाई",
    "totalEarning": "एकूण कमाई",
    "chatEarning": "चॅट कमाई",
    "callEarning": "कॉल कमाई",
    "remediesLeft": "उपाय बाकी",
    "waitingQueue": "प्रतीक्षा रांग",
    "nextInLine": "पुढील ओळीत",
    "reportEarning": "कमाईचा अहवाल द्या",
    "suggestedRemediesEarning": "सुचवलेले उपाय कमाई",
    "help": "मदत करा ",
    "orderId": "ऑर्डर आयडी :  ",
    "gender": "लिंग : ",
    "dob": "डीओबी : ",
    "pob": "पीओबी : ",
    "orderDateTime": "ऑर्डरची तारीख-वेळ : ",
    "rate": "दर : ",
    "duration": "कालावधी : ",
    "priceChangeCondition": "किंमत बदल विनंतीसाठी अटी",
    "unBlockMsg":
        "तुम्ही या वापरकर्त्याला अनब्लॉक केल्यास, ते पुन्हा तुमच्याशी प्लॅटफॉर्मवर कनेक्ट होऊ शकतील.",
    "refund": "परतावा",
    "liveGifts": "थेट भेटवस्तू",
    "remedysuggested": "उपाय सुचवला",
    "wallet": "पाकीट",
    "all": "सर्व",
    "suggest": "सूचित",
    "suggestRemedies": "उपाय सुचवा"
  };
}
