name: divine_astrologer
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  aws_s3_upload: ^1.5.0
  badges: ^3.1.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  chips_choice: ^3.0.0
  compress_images_flutter: ^0.0.3+5
  connectivity_plus: ^4.0.1
  contacts_service: ^0.6.3
  country_state_city: ^0.1.6
  cupertino_icons: ^1.0.2
  custom_rating_bar: ^2.0.5
  custom_timer: ^0.2.3
  device_info_plus: ^9.0.3
  dropdown_button2: ^2.3.7
  emoji_picker_flutter: ^1.6.1
  file_picker: ^6.1.1
  firebase_core: ^2.15.0
  firebase_database: ^10.2.3
  firebase_messaging: ^14.6.5
  flutter:
    sdk: flutter
  flutter_expanded_tile: ^0.3.7
  flutter_holo_date_picker: ^1.1.0
  flutter_html: ^3.0.0-beta.2
  flutter_image_compress: ^2.0.4
  flutter_local_notifications: ^15.1.0+1
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  flutter_switch: ^0.3.2
  fluttertoast: ^8.2.2
  get: ^4.6.5
  get_storage: ^2.1.1
  hive_flutter: ^1.1.0
  html: ^0.15.4
  image_cropper: null
  image_picker: ^1.0.2
  intl: ^0.18.0
  lottie: ^2.6.0
  percent_indicator: ^4.2.3
  permission_handler: any
  photo_view: ^0.14.0
  pin_input_text_field: ^4.5.1
  pinput: ^3.0.1
  readmore: ^2.2.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  socket_io_client: ^2.0.3+1
  svgaplayer_flutter: ^2.2.0
  syncfusion_flutter_gauges: ^23.2.7
  url_launcher: ^6.1.12
  video_trimmer: ^2.1.0
  youtube_player_flutter: ^8.1.2
  zego_uikit_prebuilt_call: ^3.17.11
  zego_uikit_prebuilt_live_streaming: ^2.23.0
  zego_uikit_signaling_plugin: ^2.7.1
  social_media_recorder: ^1.1.12
  voice_message_package: ^2.1.2

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  build_runner: any
  flutter_gen: ^5.3.1
  flutter_gen_runner: any
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/svg/
    - assets/svga/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
    - family: NotoSans
      fonts:
        - asset: assets/fonts/noto_sans/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/noto_sans/NotoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/noto_sans/NotoSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/noto_sans/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/noto_sans/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/noto_sans/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/noto_sans/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/noto_sans/NotoSans-Thin.ttf
          weight: 100

    - family: Metropolis
      fonts:
        - asset: assets/fonts/metropolis/Metropolis-Bold.otf
          weight: 700
        - asset: assets/fonts/metropolis/Metropolis-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/metropolis/Metropolis-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/metropolis/Metropolis-Light.otf
          weight: 300
        - asset: assets/fonts/metropolis/Metropolis-Medium.otf
          weight: 500
        - asset: assets/fonts/metropolis/Metropolis-Regular.otf
          weight: 400
        - asset: assets/fonts/metropolis/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/metropolis/Metropolis-Thin.otf
          weight: 100
