name: divine_astrologer
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.1.4

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  aws_s3_upload: ^1.5.0
  badges: ^3.1.2
  flutter_pdfview:
  syncfusion_flutter_gauges:
  path_provider: ^2.1.4
  screenshot: ^3.0.0
  syncfusion_flutter_signaturepad:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  camera: ^0.10.5+9
  in_app_update: ^4.2.2
  chips_choice: ^3.0.0
  compress_images_flutter: ^0.0.3+5
  connectivity_plus: ^4.0.1
  contacts_service: ^0.6.3
  country_state_city: ^0.1.6
  video_player: ^2.8.3
  cupertino_icons: ^1.0.2
  custom_rating_bar: ^2.0.5
  custom_timer: ^0.2.3
  device_info_plus: ^10.1.0
  dropdown_button2: ^2.3.7
  emoji_picker_flutter: ^1.6.1
  file_picker: ^8.0.6
  firebase_database: ^11.0.3
  firebase_core: ^3.2.0
  firebase_messaging: ^15.1.2
  android_intent_plus: ^2.0.2
  flutter:
    sdk: flutter
  flutter_expanded_tile: ^0.4.0
  flutter_holo_date_picker: ^1.1.0
  flutter_html: ^3.0.0-beta.2
  marquee: ^2.2.3
  flutter_widget_from_html: ^0.15.0
  flutter_image_compress: ^2.0.4
  flutter_local_notifications: ^17.2.2
  flutter_screenutil: ^5.8.4
  flutter_svg:
  flutter_switch: ^0.3.2
  fluttertoast: ^8.2.2
  simple_html_css: ^5.0.0
  get: ^4.6.5
  get_storage: ^2.1.1
  #html: ^0.15.4
  image_cropper: null
  image_picker: ^1.1.2
  pdf:
  printing: any

  swipe_to: ^1.0.6


  intl: ^0.18.0
  lottie: ^2.6.0
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.0
  photo_view: ^0.14.0

  pin_input_text_field: ^4.5.1
  pinput: ^3.0.1
  readmore: ^2.2.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
#  social_media_recorder: ^1.1.12
  socket_io_client: ^2.0.3+1
  audio_waveforms: ^1.0.4
  svgaplayer_flutter: ^2.2.0

  url_launcher: ^6.1.12
  video_trimmer: ^3.0.1
  voice_message_package: ^2.1.2
  youtube_player_flutter: ^8.1.2
  firebase_remote_config: ^5.0.4
  firebase_crashlytics: ^4.0.3

  dynamic_height_grid_view: ^0.0.4
  dio: ^5.4.0
  after_layout: ^1.2.0
  flutter_broadcasts: ^0.4.0
  animated_toggle_switch: ^0.8.0
  overlay_support: ^2.1.0
  transparent_image: ^2.0.1
  hive: ^2.0.5
  dio_cache_interceptor: ^3.3.0
  dio_cache_interceptor_hive_store: ^3.2.0
  flutter_cache_manager: ^3.3.1
  firebase_auth: ^5.1.2
  package_info_plus:

  flutter_timer_countdown: ^1.0.7
  flutter_keyboard_visibility: ^6.0.0
  app_settings: ^5.1.1
  truecaller_sdk: ^1.0.0
  flutter_overlay_window: ^0.4.3
  velocity_x: ^4.2.1
  uuid: ^4.3.2
  flutter_json_viewer: ^1.0.1
  device_apps: ^2.2.0
  # flutter_screen_recording: ^2.0.10
  # overlapped_carousel: ^1.0.1
  # coverflow: ^2.0.3
  random_name_generator: ^1.2.0
  dotted_border: ^2.1.0
  audioplayers: ^6.0.0
  simple_waveform_progressbar:
  speed_test_dart: ^1.0.4+1
  shimmer: ^3.0.0
  cron: ^0.6.0
  cloud_firestore: any

  zego_uikit_signaling_plugin: ^2.8.4
  zego_uikit_prebuilt_call: ^4.15.8
  zego_uikit_prebuilt_live_streaming: ^3.12.8
  zego_express_engine: ^3.16.2
  zego_uikit_beauty_plugin: ^1.7.2
  flutter_speed_dial: ^5.0.0+1
  tutorial_coach_mark: ^1.2.11
  animated_custom_dropdown: ^3.1.1
  easy_debounce: ^2.0.3
  camerax: ^0.1.2
  webview_flutter: ^4.8.0
  sms_autofill: ^2.3.1
  network_info_plus: ^6.0.1
  # awesome_notifications: ^0.9.3+1




dependency_overrides:
#  zego_uikit: ^2.23.0
  firebase_messaging_platform_interface: ^4.5.45
  fading_edge_scrollview: ^4.1.1
  intl: ^0.18.1

dev_dependencies:

  build_runner: any
  flutter_gen: ^5.3.1
  flutter_gen_runner: any
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/svg/
    - assets/docx/
    - assets/
  fonts:
    - family: MrsSaintDelafield
      fonts:
        - asset: assets/fonts/MrsSaintDelafield-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
    - family: NotoSans
      fonts:
        - asset: assets/fonts/noto_sans/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/noto_sans/NotoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/noto_sans/NotoSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/noto_sans/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/noto_sans/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/noto_sans/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/noto_sans/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/noto_sans/NotoSans-Thin.ttf
          weight: 100

    - family: Metropolis
      fonts:
        - asset: assets/fonts/metropolis/Metropolis-Bold.otf
          weight: 700
        - asset: assets/fonts/metropolis/Metropolis-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/metropolis/Metropolis-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/metropolis/Metropolis-Light.otf
          weight: 300
        - asset: assets/fonts/metropolis/Metropolis-Medium.otf
          weight: 500
        - asset: assets/fonts/metropolis/Metropolis-Regular.otf
          weight: 400
        - asset: assets/fonts/metropolis/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/metropolis/Metropolis-Thin.otf
          weight: 100
