name: divine_astrologer
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.2.0
  flutter_screenutil: ^5.8.4
  connectivity_plus: ^4.0.1
  #http: ^1.1.0
  readmore: ^2.2.0
  percent_indicator: ^4.2.3
  custom_rating_bar: ^2.0.5
  flutter_switch: ^0.3.2
  flutter_holo_date_picker: ^1.1.0
  flutter_svg: ^2.0.7
  dropdown_button2: ^2.3.7
  intl: ^0.18.0
  syncfusion_flutter_gauges: ^22.2.7
  flutter_expanded_tile: ^0.3.7
  chips_choice: ^3.0.0
  carousel_slider: ^4.2.1
  country_state_city: ^0.1.6
  firebase_core: ^2.15.0
  firebase_database: ^10.2.4
  firebase_messaging: ^14.6.5
  get_storage: ^2.1.1
  html: ^0.15.4
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.12
  zego_uikit_prebuilt_live_streaming: ^2.15.3
  zego_uikit_signaling_plugin: ^2.3.2
  svgaplayer_flutter: ^2.2.0
  permission_handler: ^10.4.3
  image_picker: ^1.0.2
  image_cropper:
  aws_s3_upload: ^1.5.0
  compress_images_flutter: ^0.0.3+5
  fluttertoast: ^8.2.2
  video_trimmer: ^2.1.0
  flutter_image_compress: ^2.0.4
  lottie: ^2.6.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen: ^5.3.1

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-ExtraBold.ttf
        weight: 800
